import { AddAgentTitlesAndLabelsGetter } from "@realestatemanager/shared";
import { TableColumn } from "../../components/ReusableTable";
import { InputType } from "../../constants/Constant";

const getterInstance: AddAgentTitlesAndLabelsGetter = new AddAgentTitlesAndLabelsGetter();

export const agentDefaultColumns: TableColumn[] = [
    {
        header: getterInstance.firstNameTitle,
        accessor: getterInstance.firstNameName,
        inputType: InputType.STRING,
        isURL: false,
        showColumn: true,
        isDollarAmount: false,
        isSortable: true,
        isEditable: true,
    },
    {
        header: getterInstance.lastNameTitle,
        accessor: getterInstance.lastNameName,
        inputType: InputType.STRING,
        isURL: false,
        showColumn: true,
        isDollarAmount: false,
        isSortable: true,
        isEditable: true,
    },
    {
        header: "Full Name",  // Come back to this 
        accessor: "fullName",
        inputType: InputType.STRING,
        isURL: false,
        showColumn: true,
        isDollarAmount: false,
        isSortable: true,
    },
    {
        header: getterInstance.websiteTitle,
        accessor: getterInstance.websiteName,
        inputType: InputType.STRING,
        isURL: true,
        showColumn: true,
        isDollarAmount: false,
        isSortable: true,
        isEditable: true,
    },
    {
        header: getterInstance.companyNameTitle,
        accessor: getterInstance.companyNameName,
        inputType: InputType.STRING,
        isURL: false,
        showColumn: true,
        isDollarAmount: false,
        isSortable: true,
        isEditable: true,
    },
    {
        header: getterInstance.phoneNumberTitle,
        accessor: getterInstance.phoneNumberName,
        inputType: InputType.STRING,
        isURL: false,
        showColumn: true,
        isDollarAmount: false,
        isSortable: true,
        isEditable: true,
    },
    {
        header: getterInstance.emailTitle,
        accessor: getterInstance.emailName,
        inputType: InputType.STRING,
        isURL: false,
        showColumn: true,
        isDollarAmount: false,
        isSortable: true,
        isEditable: true,
    },
    {
        header: getterInstance.countryTitle,
        accessor: getterInstance.countryName,
        inputType: InputType.STRING,
        isURL: false,
        showColumn: true,
        isDollarAmount: false,
        isSortable: true,
    },
    {
        header: getterInstance.stateTitle,
        accessor: getterInstance.stateName,
        inputType: InputType.STRING,
        isURL: false,
        showColumn: true,
        isDollarAmount: false,
        isSortable: true,
    },
    {
        header: getterInstance.agentTypeTitle,
        accessor: getterInstance.agentTypeName,
        inputType: InputType.STRING,
        isURL: false,
        showColumn: true,
        isDollarAmount: false,
        isSortable: true,
    },
];