import { AddPropertyTitlesAndLabelsGetter } from "@realestatemanager/types";
import { TableColumn } from "../../components/ReusableTable";
import { InputType } from "../../constants/Constant";

const getterInstance: AddPropertyTitlesAndLabelsGetter = new AddPropertyTitlesAndLabelsGetter();

export const dummyDataDefaultColumns: TableColumn[] = [
    {
        header: getterInstance.zillowURLTitle,
        accessor: getterInstance.zillowURLName,
        inputType: InputType.STRING,
        isURL: false,
        showColumn: true,
        isDollarAmount: false,
        isSortable: false,
    },
    {
        header: getterInstance.fullAddressTitle,
        accessor: getterInstance.fullAddressName,
        inputType: InputType.STRING,
        isURL: false,
        showColumn: true,
        isDollarAmount: false,
        isSortable: false,
    },
    {
        header: getterInstance.stateTitle,
        accessor: getterInstance.stateName,
        inputType: InputType.STRING,
        isURL: false,
        showColumn: true,
        isDollarAmount: false,
        isSortable: false,
    },
    {
        header: getterInstance.zipcodeTitle,
        accessor: getterInstance.zipcodeName,
        inputType: InputType.STRING,
        isURL: false,
        showColumn: true,
        isDollarAmount: false,
        isSortable: false,
    },
    {
        header: getterInstance.cityTitle,
        accessor: getterInstance.cityName,
        inputType: InputType.STRING,
        isURL: false,
        showColumn: true,
        isDollarAmount: false,
        isSortable: false,
    },
    {
        header: getterInstance.countyTitle,
        accessor: getterInstance.countyName,
        inputType: InputType.STRING,
        isURL: false,
        showColumn: true,
        isDollarAmount: false,
        isSortable: false,
    },
    {
        header: getterInstance.countryTitle,
        accessor: getterInstance.countryName,
        inputType: InputType.STRING,
        isURL: false,
        showColumn: true,
        isDollarAmount: false,
        isSortable: false,
    },
    {
        header: getterInstance.streetAddressTitle,
        accessor: getterInstance.streetAddressName,
        inputType: InputType.STRING,
        isURL: false,
        showColumn: true,
        isDollarAmount: false,
        isSortable: false,
    },
    {
        header: getterInstance.apartmentNumberTitle,
        accessor: getterInstance.apartmentNumberName,
        inputType: InputType.STRING,
        isURL: false,
        showColumn: true,
        isDollarAmount: false,
        isSortable: false,
    },
    {
        header: getterInstance.longitudeTitle,
        accessor: getterInstance.longitudeName,
        inputType: InputType.STRING,
        isURL: false,
        showColumn: true,
        isDollarAmount: false,
        isSortable: false,
    },
    {
        header: getterInstance.latitudeTitle,
        accessor: getterInstance.latitudeName,
        inputType: InputType.STRING,
        isURL: false,
        showColumn: true,
        isDollarAmount: false,
        isSortable: false,
    },
    {
        header: getterInstance.numberOfDaysOnMarketTitle,
        accessor: getterInstance.numberOfDaysOnMarketName,
        inputType: InputType.STRING,
        isURL: false,
        showColumn: true,
        isDollarAmount: false,
        isSortable: false,
    },
    {
        header: getterInstance.elementarySchoolRatingTitle,
        accessor: getterInstance.elementarySchoolRatingName,
        inputType: InputType.STRING,
        isURL: false,
        showColumn: true,
        isDollarAmount: false,
        isSortable: false,
    },
    {
        header: getterInstance.middleSchoolRatingTitle,
        accessor: getterInstance.middleSchoolRatingName,
        inputType: InputType.STRING,
        isURL: false,
        showColumn: true,
        isDollarAmount: false,
        isSortable: false,
    },
    {
        header: getterInstance.highSchoolRatingTitle,
        accessor: getterInstance.highSchoolRatingName,
        inputType: InputType.STRING,
        isURL: false,
        showColumn: true,
        isDollarAmount: false,
        isSortable: false,
    },
    {
        header: getterInstance.numberOfBedroomsTitle,
        accessor: getterInstance.numberOfBedroomsName,
        inputType: InputType.STRING,
        isURL: false,
        showColumn: true,
        isDollarAmount: false,
        isSortable: false,
    },
    {
        header: getterInstance.numberOfFullBathroomsTitle,
        accessor: getterInstance.numberOfFullBathroomsName,
        inputType: InputType.STRING,
        isURL: false,
        showColumn: true,
        isDollarAmount: false,
        isSortable: false,
    },
    {
        header: getterInstance.numberOfHalfBathroomsTitle,
        accessor: getterInstance.numberOfHalfBathroomsName,
        inputType: InputType.STRING,
        isURL: false,
        showColumn: true,
        isDollarAmount: false,
        isSortable: false,
    },
    {
        header: getterInstance.squareFeetTitle,
        accessor: getterInstance.squareFeetName,
        inputType: InputType.STRING,
        isURL: false,
        showColumn: true,
        isDollarAmount: false,
        isSortable: false,
    },
    {
        header: getterInstance.acresTitle,
        accessor: getterInstance.acresName,
        inputType: InputType.STRING,
        isURL: false,
        showColumn: true,
        isDollarAmount: false,
        isSortable: false,
    },
    {
        header: getterInstance.yearBuiltTitle,
        accessor: getterInstance.yearBuiltName,
        inputType: InputType.STRING,
        isURL: false,
        showColumn: true,
        isDollarAmount: false,
        isSortable: false,
    },
    {
        header: getterInstance.hasGarageTitle,
        accessor: getterInstance.hasGarageName,
        inputType: InputType.STRING,
        isURL: false,
        showColumn: true,
        isDollarAmount: false,
        isSortable: false,
    },
    {
        header: getterInstance.hasPoolTitle,
        accessor: getterInstance.hasPoolName,
        inputType: InputType.STRING,
        isURL: false,
        showColumn: true,
        isDollarAmount: false,
        isSortable: false,
    },
    {
        header: getterInstance.hasBasementTitle,
        accessor: getterInstance.hasBasementName,
        inputType: InputType.STRING,
        isURL: false,
        showColumn: true,
        isDollarAmount: false,
        isSortable: false,
    },
    {
        header: getterInstance.propertyTypeTitle,
        accessor: getterInstance.propertyTypeName,
        inputType: InputType.STRING,
        isURL: false,
        showColumn: true,
        isDollarAmount: false,
        isSortable: false,
    },
    {
        header: getterInstance.propertyStatusTitle,
        accessor: getterInstance.propertyStatusName,
        inputType: InputType.STRING,
        isURL: false,
        showColumn: true,
        isDollarAmount: false,
        isSortable: false,
    },
    {
        header: getterInstance.listingPriceTitle,
        accessor: getterInstance.listingPriceName,
        inputType: InputType.STRING,
        isURL: false,
        showColumn: true,
        isDollarAmount: false,
        isSortable: false,
    },
    {
        header: getterInstance.zestimateTitle,
        accessor: getterInstance.zestimateName,
        inputType: InputType.STRING,
        isURL: false,
        showColumn: true,
        isDollarAmount: false,
        isSortable: false,
    },
    {
        header: getterInstance.zillowRentEstimateTitle,
        accessor: getterInstance.zillowRentEstimateName,
        inputType: InputType.STRING,
        isURL: false,
        showColumn: true,
        isDollarAmount: false,
        isSortable: false,
    },
    {
        header: getterInstance.zestimateRangeLowTitle,
        accessor: getterInstance.zestimateRangeLowName,
        inputType: InputType.STRING,
        isURL: false,
        showColumn: true,
        isDollarAmount: false,
        isSortable: false,
    },
    {
        header: getterInstance.zestimateRangeHighTitle,
        accessor: getterInstance.zestimateRangeHighName,
        inputType: InputType.STRING,
        isURL: false,
        showColumn: true,
        isDollarAmount: false,
        isSortable: false,
    },
    {
        header: getterInstance.zillowMonthlyPropertyTaxAmountTitle,
        accessor: getterInstance.zillowMonthlyPropertyTaxAmountName,
        inputType: InputType.STRING,
        isURL: false,
        showColumn: true,
        isDollarAmount: false,
        isSortable: false,
    },
    {
        header: getterInstance.zillowMonthlyHomeInsuranceAmountTitle,
        accessor: getterInstance.zillowMonthlyHomeInsuranceAmountName,
        inputType: InputType.STRING,
        isURL: false,
        showColumn: true,
        isDollarAmount: false,
        isSortable: false,
    },
    {
        header: getterInstance.zillowMonthlyHOAFeesAmountTitle,
        accessor: getterInstance.zillowMonthlyHOAFeesAmountName,
        inputType: InputType.STRING,
        isURL: false,
        showColumn: true,
        isDollarAmount: false,
        isSortable: false,
    },
    {
        header: getterInstance.descriptionTitle,
        accessor: getterInstance.descriptionName,
        inputType: InputType.STRING,
        isURL: false,
        showColumn: true,
        isDollarAmount: false,
        isSortable: false,
    },
];