import { TableColumn } from "../../components/ReusableTable";
import { InputType } from "../../constants/Constant";

export const dummyDataDefaultColumns: TableColumn[] = [
    {
        header: "First Name",
        accessor: "firstName",
        inputType: InputType.STRING,
        isURL: false,
        showColumn: true,
        isDollarAmount: false,
        isSortable: false,
    },
    {
        header: "Last Name",
        accessor: "lastName",
        inputType: InputType.STRING,
        isURL: false,
        showColumn: true,
        isDollarAmount: false,
        isSortable: false,
    },
    {
        header: "Full Name",
        accessor: "fullName",
        inputType: InputType.STRING,
        isURL: false,
        showColumn: true,
        isDollarAmount: false,
        isSortable: false,
    },
    {
        header: "Website",
        accessor: "website",
        inputType: InputType.STRING,
        isURL: false,
        showColumn: true,
        isDollarAmount: false,
        isSortable: false,
    },
    {
        header: "Company Name",
        accessor: "companyName",
        inputType: InputType.STRING,
        isURL: false,
        showColumn: true,
        isDollarAmount: false,
        isSortable: false,
    },
    {
        header: "Phone Number",
        accessor: "phoneNumber",
        inputType: InputType.STRING,
        isURL: false,
        showColumn: true,
        isDollarAmount: false,
        isSortable: false,
    },
    {
        header: "Email",
        accessor: "email",
        inputType: InputType.STRING,
        isURL: false,
        showColumn: true,
        isDollarAmount: false,
        isSortable: false,
    },
    {
        header: "Country",
        accessor: "country",
        inputType: InputType.STRING,
        isURL: false,
        showColumn: true,
        isDollarAmount: false,
        isSortable: false,
    },
    {
        header: "State",
        accessor: "state",
        inputType: InputType.STRING,
        isURL: false,
        showColumn: true,
        isDollarAmount: false,
        isSortable: false,
    },
    {
        header: "Agent Type",
        accessor: "agentType",
        inputType: InputType.STRING,
        isURL: false,
        showColumn: true,
        isDollarAmount: false,
        isSortable: false,
    },
];