// InvestmentBreakdownColumns.ts

import { TableColumn } from "../../components/ReusableTable";

export const standardBreakdownColumns: TableColumn[] = [
    {
        header: "Year",
        accessor: "year",
        isURL: false,
        showColumn: true,
        isDollarAmount: false,
        isSortable: false,
    },
    {
        header: "Month",
        accessor: "month",
        isURL: false,
        showColumn: true,
        isDollarAmount: false,
        isSortable: false,
    },
    {
        header: "Date",
        accessor: "date",
        isURL: false,
        showColumn: true,
        isDollarAmount: false,
        isSortable: false,
    },
    {
        header: "Mortgage Amount",
        accessor: "mortgageAmount",
        isURL: false,
        showColumn: true,
        isDollarAmount: true,
        isSortable: false,
        detailedDescription: `Mortgage Amount + PMI`,
    },
    {
        header: "Total Interest Paid",
        accessor: "totalInterestPaid",
        isURL: false,
        showColumn: true,
        isDollarAmount: true,
        isSortable: false,
    },
    {
        header: "Total Principal Paid",
        accessor: "totalPrincipalPaid",
        isURL: false,
        showColumn: true,
        isDollarAmount: true,
        isSortable: false,
    },
    {
        header: "Remaining Balance",
        accessor: "remainingBalance",
        isURL: false,
        showColumn: true,
        isDollarAmount: true,
        isSortable: false,
    },
    {
        header: "Rent Estimate",
        accessor: "rentEstimate",
        isURL: false,
        showColumn: true,
        isDollarAmount: true,
        isSortable: false,
    },
    {
        header: "Monthly Income",
        accessor: "monthlyIncome",
        isURL: false,
        showColumn: true,
        isDollarAmount: true,
        isSortable: false,
    },
    {
        header: "Monthly Expenses",
        accessor: "monthlyExpenses",
        isURL: false,
        showColumn: true,
        isDollarAmount: true,
        isSortable: false,
    },
    {
        header: "Monthly Cash Flow",
        accessor: "monthlyCashFlow",
        isURL: false,
        showColumn: true,
        isDollarAmount: true,
        isSortable: false,
        detailedDescription: `Rent Estimate - (Monthly Payment + Operational Costs)`,
    },
    {
        header: "Accumulated Cash Flow",
        accessor: "accumulatedCashFlow",
        isURL: false,
        showColumn: true,
        isDollarAmount: true,
        isSortable: false,
    },
    {
        header: "Appreciation Amount",
        accessor: "appreciationAmount",
        isURL: false,
        showColumn: true,
        isDollarAmount: true,
        isSortable: false
    },
];

export const mortgageBreakdownColumns: TableColumn[] = [
    {
        header: "Year",
        accessor: "year",
        isURL: false,
        showColumn: true,
        isDollarAmount: false,
        isSortable: false,
    },
    {
        header: "Month",
        accessor: "month",
        isURL: false,
        showColumn: true,
        isDollarAmount: false,
        isSortable: false,
    },
    {
        header: "Date",
        accessor: "date",
        isURL: false,
        showColumn: true,
        isDollarAmount: false,
        isSortable: false,
    },
    {
        header: "Mortgage Amount",
        accessor: "mortgageAmount",
        isURL: false,
        showColumn: true,
        isDollarAmount: true,
        isSortable: false,
        detailedDescription: `Mortgage Amount + PMI`,
    },
    {
        header: "PMI Amount",
        accessor: "pmiAmount",
        isURL: false,
        showColumn: true,
        isDollarAmount: true,
        isSortable: false,
    },
    {
        header: "Interest Payment",
        accessor: "interestPayment",
        isURL: false,
        showColumn: true,
        isDollarAmount: true,
        isSortable: false,
    },
    {
        header: "Principal Payment",
        accessor: "principalPayment",
        isURL: false,
        showColumn: true,
        isDollarAmount: true,
        isSortable: false,
    },
    {
        header: "Interest Payment",
        accessor: "interestPayment",
        isURL: false,
        showColumn: true,
        isDollarAmount: true,
        isSortable: false,
    },
    {
        header: "Percentage of Interest (%)",
        accessor: "percentageOfInterest",
        isURL: false,
        showColumn: true,
        isDollarAmount: false,
        isSortable: false,
        addSuffix: '%',
    },
    {
        header: "Percentage of Principal (%)",
        accessor: "percentageOfPrincipal",
        isURL: false,
        showColumn: true,
        isDollarAmount: false,
        isSortable: false,
        addSuffix: '%',
    },
    {
        header: "Total Interest Paid",
        accessor: "totalInterestPaid",
        isURL: false,
        showColumn: true,
        isDollarAmount: true,
        isSortable: false,
    },
    {
        header: "Total Principal Paid",
        accessor: "totalPrincipalPaid",
        isURL: false,
        showColumn: true,
        isDollarAmount: true,
        isSortable: false,
    },
    {
        header: "Remaining Balance",
        accessor: "remainingBalance",
        isURL: false,
        showColumn: true,
        isDollarAmount: true,
        isSortable: false,
    },
];

export const investmentBreakdownColumns: TableColumn[] = [
    {
        header: "Year",
        accessor: "year",
        isURL: false,
        showColumn: true,
        isDollarAmount: false,
        isSortable: false,
    },
    {
        header: "Month",
        accessor: "month",
        isURL: false,
        showColumn: true,
        isDollarAmount: false,
        isSortable: false,
    },
    {
        header: "Date",
        accessor: "date",
        isURL: false,
        showColumn: true,
        isDollarAmount: false,
        isSortable: false,
    },
    {
        header: "Rent Estimate",
        accessor: "rentEstimate",
        isURL: false,
        showColumn: true,
        isDollarAmount: true,
        isSortable: false,
    },
    {
        header: "Monthly Income",
        accessor: "monthlyIncome",
        isURL: false,
        showColumn: true,
        isDollarAmount: true,
        isSortable: false,
    },
    {
        header: "Monthly Expenses",
        accessor: "monthlyExpenses",
        isURL: false,
        showColumn: true,
        isDollarAmount: true,
        isSortable: false,
    },
    {
        header: "Monthly Cash Flow",
        accessor: "monthlyCashFlow",
        isURL: false,
        showColumn: true,
        isDollarAmount: true,
        isSortable: false,
        detailedDescription: `Rent Estimate - (Monthly Payment + Operational Costs)`,
    },
    {
        header: "Accumulated Cash Flow",
        accessor: "accumulatedCashFlow",
        isURL: false,
        showColumn: true,
        isDollarAmount: true,
        isSortable: false,
    },
    {
        header: "Equity Amount",
        accessor: "equityAmount",
        isURL: false,
        showColumn: true,
        isDollarAmount: true,
        isSortable: false,
        detailedDescription: `Equity Amount`,
    },
    {
        header: "Net Operating Income (NOI)",
        accessor: "netOperatingIncome",
        isURL: false,
        showColumn: true,
        isDollarAmount: true,
        isSortable: false,
        detailedDescription: `Net Operating Income (NOI)`,
    },
    {
        header: "Accumulated Net Operating Income (NOI)",
        accessor: "accumulatedNetOperatingIncome",
        isURL: false,
        showColumn: true,
        isDollarAmount: true,
        isSortable: false,
        detailedDescription: `Accumulated Net Operation Income (NOI)`,
    },
    {
        header: "Cap Rate (%)",
        accessor: "capRate",
        isURL: false,
        showColumn: true,
        isDollarAmount: false,
        isSortable: false,
        detailedDescription: `Cap Rate`,
        addSuffix: `%`
    },
    {
        header: "Return On Investment (ROI %)",
        accessor: "returnOnInvestment",
        isURL: false,
        showColumn: true,
        isDollarAmount: false,
        isSortable: false,
        detailedDescription: `Return On Investment (ROI)`,
        addSuffix: `%`
    },
    {
        header: "Cash On Cash Return (COC %)",
        accessor: "cashOnCashReturn",
        isURL: false,
        showColumn: true,
        isDollarAmount: false,
        isSortable: false,
        detailedDescription: `Cash On Cash Return (COC)`,
        addSuffix: `%`,
    },
    {
        header: "Monthly Net Income",
        accessor: "monthlyNetIncome",
        isURL: false,
        showColumn: true,
        isDollarAmount: true,
        isSortable: false,
        detailedDescription: `Monthly Net Income`,
    },
    {
        header: "Accumulated Net Income",
        accessor: "accumulatedNetIncome",
        isURL: false,
        showColumn: true,
        isDollarAmount: true,
        isSortable: false,
        detailedDescription: `Accumulated Net Income`,
    },
    {
        header: "Appreciation Amount",
        accessor: "appreciationAmount",
        isURL: false,
        showColumn: true,
        isDollarAmount: true,
        isSortable: false
    },
];

export const expensesBreakdownColumns: TableColumn[] = [
    {
        header: "Year",
        accessor: "year",
        isURL: false,
        showColumn: true,
        isDollarAmount: false,
        isSortable: false,
    },
    {
        header: "Month",
        accessor: "month",
        isURL: false,
        showColumn: true,
        isDollarAmount: false,
        isSortable: false,
    },
    {
        header: "Date",
        accessor: "date",
        isURL: false,
        showColumn: true,
        isDollarAmount: false,
        isSortable: false,
    },
    {
        header: "Property Management Amount",
        accessor: "propertyManagementAmount",
        isURL: false,
        showColumn: true,
        isDollarAmount: true,
        isSortable: false,
    },
    {
        header: "Vacancy Amount",
        accessor: "vacancyAmount",
        isURL: false,
        showColumn: true,
        isDollarAmount: true,
        isSortable: false,
    },
    {
        header: "Maintenance Amount",
        accessor: "maintenanceAmount",
        isURL: false,
        showColumn: true,
        isDollarAmount: true,
        isSortable: false,
    },
    {
        header: "Cap Ex Reserve Amount",
        accessor: "capExReserveAmount",
        isURL: false,
        showColumn: true,
        isDollarAmount: true,
        isSortable: false,
    },
    {
        header: "Other Expense Amount",
        accessor: "otherExpenseAmount",
        isURL: false,
        showColumn: true,
        isDollarAmount: true,
        isSortable: false,
    },
    {
        header: "Operational Costs",
        accessor: "operationalCosts",
        isURL: false,
        showColumn: true,
        isDollarAmount: true,
        isSortable: true,
        detailedDescription: `Property Management Amount + 
                        Vacancy Amount +
                        Maintenance Amount +
                        Other Expenses Amount +
                        CapEx Reserve Amount`,
    },
    {
        header: "Property Tax Amount",
        accessor: "propertyTaxAmount",
        isURL: false,
        showColumn: true,
        isDollarAmount: true,
        isSortable: false,
    },
    {
        header: "Monthly Home Insurance Amount",
        accessor: "monthlyHomeInsuranceAmount",
        isURL: false,
        showColumn: true,
        isDollarAmount: true,
        isSortable: false,
    },
    {
        header: "Monthly HOA Fees Amount",
        accessor: "monthlyHOAFeesAmount",
        isURL: false,
        showColumn: true,
        isDollarAmount: true,
        isSortable: false,
    },
    {
        header: "Fixed Costs",
        accessor: "fixedCosts",
        isURL: false,
        showColumn: true,
        isDollarAmount: true,
        isSortable: true,
        detailedDescription: `Property Tax Amount +
                                Monthly Home Insurance Amount +
                                Monthly HOA Fees Amount`,
    },
    {
        header: "Mortgage Amount",
        accessor: "mortgageAmount",
        isURL: false,
        showColumn: true,
        isDollarAmount: true,
        isSortable: false,
        detailedDescription: `Mortgage Amount + PMI`,
    },
    {
        header: "PMI Amount",
        accessor: "pmiAmount",
        isURL: false,
        showColumn: true,
        isDollarAmount: true,
        isSortable: false,
    },
    {
        header: "Monthly Payment",
        accessor: "monthlyPayment",
        isURL: false,
        showColumn: true,
        isDollarAmount: true,
        isSortable: false,
        detailedDescription: `Mortgage Amount +
                                Property Tax Amount +
                                Monthly Home Insurance Amount +
                                Monthly HOA Fees Amount`,
    },
    {
        header: "Monthly Payment + Operational Costs",
        accessor: "monthlyPaymentAndOperationalCosts",
        isURL: false,
        showColumn: true,
        isDollarAmount: true,
        isSortable: false,
    },
];