import { TableColumn } from "../../components/ReusableTable";
import { InputType } from "../../constants/Constant";

export const rentCastDetailsColumns: TableColumn[] = [
    {
        header: "Api Key Name",
        accessor: "apiKeyName",
        inputType: InputType.STRING,
        isURL: false,
        showColumn: true,
        isDollarAmount: false,
        isSortable: true,
    },
    {
        header: "Can make API call",
        accessor: "canMakeApiCalls",
        inputType: InputType.STRING,
        isURL: false,
        showColumn: true,
        isDollarAmount: false,
        isSortable: true,
    },
    {
        header: "Api Calls Made this Month",
        accessor: "apiCallsThisMonth",
        inputType: InputType.NUMBER,
        isURL: false,
        showColumn: true,
        isDollarAmount: false,
        isSortable: true,
    },
    {
        header: "Remaining number of free API calls left",
        accessor: "remainingNumberOfFreeApiCalls",
        inputType: InputType.NUMBER,
        isURL: false,
        showColumn: true,
        isDollarAmount: false,
        isSortable: true,
    },
    {
        header: "Days into billing period",
        accessor: "daysIntoBillingPeriod",
        inputType: InputType.NUMBER,
        isURL: false,
        showColumn: true,
        isDollarAmount: false,
        isSortable: true,
    },
    {
        header: "Billing Period",
        accessor: "billingPeriod",
        inputType: InputType.NUMBER,
        isURL: false,
        showColumn: true,
        isDollarAmount: false,
        isSortable: true,
    },
    {
        header: "Most Recent Billing Date",
        accessor: "mostRecentBillingDate",
        inputType: InputType.STRING,
        isURL: false,
        showColumn: true,
        isDollarAmount: false,
        isSortable: false,
    },
    {
        header: "First Billed On",
        accessor: "firstBilledOn",
        inputType: InputType.STRING,
        isURL: false,
        showColumn: true,
        isDollarAmount: false,
        isSortable: false,
    },
];