import { BasicColumn, InputType, TableCellValue } from "react-ui-library-ks-dev";
import { TableColumnEnum } from "./TableColumnEnum";

type Column = {
    key: string;
    title: string;
    inputType: InputType;
    isUrl: boolean;
    isDollarAmount: boolean;
    addSuffix: string;
    showColumn: boolean;
    isEditable: boolean;
    isSortable: boolean;
    detailedDescription: string;
    routeTo?: string;
};

// Define the type for the map where each key is an enum value
export type ColumnDetailsMap = Record<TableColumnEnum, Column>;


export class TableColumnDetails<T> {

    private columnDetails: ColumnDetailsMap = {
        [TableColumnEnum.PROPERTY_TYPE]: {
            key: 'propertyType',
            title: 'Property Type',
            inputType: InputType.SELECT,
            isUrl: false,
            isDollarAmount: false,
            addSuffix: '',
            showColumn: true,
            isEditable: true,
            isSortable: true,
            detailedDescription: 'Type of property (Single Family, Multi-Family, Condo, etc.)',
            routeTo: '/property-types',
        },
        [TableColumnEnum.PROPERTY_STATUS]: {
            key: 'propertyStatus',
            title: 'Status',
            inputType: InputType.SELECT,
            isUrl: false,
            isDollarAmount: false,
            addSuffix: '',
            showColumn: true,
            isEditable: true,
            isSortable: true,
            detailedDescription: 'Current status of the property (Active, Pending, Sold, etc.)',
            routeTo: '',
        },
        [TableColumnEnum.FULL_ADDRESS]: {
            key: 'fullAddress',
            title: 'Full Address',
            inputType: InputType.ADDRESS,
            isUrl: false,
            isDollarAmount: false,
            addSuffix: '',
            showColumn: true,
            isEditable: true,
            isSortable: true,
            detailedDescription: 'Complete address of the property',
            routeTo: '/property-details',
        },
        [TableColumnEnum.STATE]: {
            key: 'state',
            title: 'State',
            inputType: InputType.SELECT,
            isUrl: false,
            isDollarAmount: false,
            addSuffix: '',
            showColumn: true,
            isEditable: true,
            isSortable: true,
            detailedDescription: 'State where the property is located',
            routeTo: '',
        },
        [TableColumnEnum.ZIP_CODE]: {
            key: 'zipCode',
            title: 'ZIP Code',
            inputType: InputType.TEXT,
            isUrl: false,
            isDollarAmount: false,
            addSuffix: '',
            showColumn: true,
            isEditable: true,
            isSortable: true,
            detailedDescription: 'ZIP code of the property location',
            routeTo: '',
        },
        [TableColumnEnum.ZILLOW_URL]: {
            key: 'zillowUrl',
            title: 'Zillow Link',
            inputType: InputType.URL,
            isUrl: true,
            isDollarAmount: false,
            addSuffix: '',
            showColumn: true,
            isEditable: true,
            isSortable: false,
            detailedDescription: 'Link to property listing on Zillow',
            routeTo: '',
        },
        [TableColumnEnum.PRICE]: {
            key: 'price',
            title: 'Price',
            inputType: InputType.MONEY,
            isUrl: false,
            isDollarAmount: true,
            addSuffix: '',
            showColumn: true,
            isEditable: true,
            isSortable: true,
            detailedDescription: 'Purchase price of the property',
            routeTo: '',
        },
        [TableColumnEnum.RENT_ESTIMATE]: {
            key: 'rentEstimate',
            title: 'Rent Estimate',
            inputType: InputType.MONEY,
            isUrl: false,
            isDollarAmount: true,
            addSuffix: '/mo',
            showColumn: true,
            isEditable: true,
            isSortable: true,
            detailedDescription: 'Estimated monthly rental income',
            routeTo: '',
        },
        [TableColumnEnum.INITIAL_COSTS]: {
            key: 'initialCosts',
            title: 'Initial Costs',
            inputType: InputType.MONEY,
            isUrl: false,
            isDollarAmount: true,
            addSuffix: '',
            showColumn: true,
            isEditable: true,
            isSortable: true,
            detailedDescription: 'Total upfront costs including closing and renovations',
            routeTo: '/cost-breakdown',
        },
        [TableColumnEnum.LOAN_AMOUNT]: {
            key: 'loanAmount',
            title: 'Loan Amount',
            inputType: InputType.MONEY,
            isUrl: false,
            isDollarAmount: true,
            addSuffix: '',
            showColumn: true,
            isEditable: true,
            isSortable: true,
            detailedDescription: 'Amount of mortgage loan',
            routeTo: '',
        },
        [TableColumnEnum.DOWN_PAYMENT_AMOUNT]: {
            key: 'downPaymentAmount',
            title: 'Down Payment',
            inputType: InputType.MONEY,
            isUrl: false,
            isDollarAmount: true,
            addSuffix: '',
            showColumn: true,
            isEditable: true,
            isSortable: true,
            detailedDescription: 'Down payment amount',
            routeTo: '',
        },
        [TableColumnEnum.ANNUAL_INTEREST_RATE]: {
            key: 'annualInterestRate',
            title: 'Interest Rate',
            inputType: InputType.PERCENTAGE,
            isUrl: false,
            isDollarAmount: false,
            addSuffix: '%',
            showColumn: true,
            isEditable: true,
            isSortable: true,
            detailedDescription: 'Annual interest rate for the mortgage',
            routeTo: '',
        },
        [TableColumnEnum.ROI]: {
            key: 'roi',
            title: 'ROI',
            inputType: InputType.PERCENTAGE,
            isUrl: false,
            isDollarAmount: false,
            addSuffix: '%',
            showColumn: true,
            isEditable: false,
            isSortable: true,
            detailedDescription: 'Return on Investment percentage',
            routeTo: '/roi-details',
        },
        [TableColumnEnum.CAP_RATE]: {
            key: 'capRate',
            title: 'Cap Rate',
            inputType: InputType.PERCENTAGE,
            isUrl: false,
            isDollarAmount: false,
            addSuffix: '%',
            showColumn: true,
            isEditable: false,
            isSortable: true,
            detailedDescription: 'Capitalization Rate (net operating income / property value)',
            routeTo: '',
        },
        [TableColumnEnum.RECURRING_COSTS]: {
            key: 'recurringCosts',
            title: 'Recurring Costs',
            inputType: InputType.MONEY,
            isUrl: false,
            isDollarAmount: true,
            addSuffix: '/mo',
            showColumn: true,
            isEditable: true,
            isSortable: true,
            detailedDescription: 'Monthly recurring expenses',
            routeTo: '/expense-breakdown',
        },
        [TableColumnEnum.INITIAL_MONTHLY_AMOUNT]: {
            key: 'initialMonthlyAmount',
            title: 'Initial Monthly Cost',
            inputType: InputType.MONEY,
            isUrl: false,
            isDollarAmount: true,
            addSuffix: '/mo',
            showColumn: true,
            isEditable: true,
            isSortable: true,
            detailedDescription: 'Initial total monthly payment',
            routeTo: '',
        },
        [TableColumnEnum.MORTGAGE]: {
            key: 'mortgage',
            title: 'Mortgage',
            inputType: InputType.MONEY,
            isUrl: false,
            isDollarAmount: true,
            addSuffix: '/mo',
            showColumn: true,
            isEditable: false,
            isSortable: true,
            detailedDescription: 'Monthly mortgage payment',
            routeTo: '/mortgage-details',
        },
        [TableColumnEnum.MONTHLY_CASH_FLOW]: {
            key: 'monthlyCashFlow',
            title: 'Monthly Cash Flow',
            inputType: InputType.MONEY,
            isUrl: false,
            isDollarAmount: true,
            addSuffix: '/mo',
            showColumn: true,
            isEditable: false,
            isSortable: true,
            detailedDescription: 'Monthly income minus expenses',
            routeTo: '/cash-flow-details',
        },
        [TableColumnEnum.YEARLY_CASH_FLOW]: {
            key: 'yearlyCashFlow',
            title: 'Yearly Cash Flow',
            inputType: InputType.MONEY,
            isUrl: false,
            isDollarAmount: true,
            addSuffix: '/yr',
            showColumn: true,
            isEditable: false,
            isSortable: true,
            detailedDescription: 'Yearly income minus expenses',
            routeTo: '',
        },
        [TableColumnEnum.NUMBER_OF_DAYS_ON_MARKET]: {
            key: 'daysOnMarket',
            title: 'Days on Market',
            inputType: InputType.NUMBER,
            isUrl: false,
            isDollarAmount: false,
            addSuffix: ' days',
            showColumn: true,
            isEditable: false,
            isSortable: true,
            detailedDescription: 'Number of days the property has been listed',
            routeTo: '',
        },
        [TableColumnEnum.DATE_LISTED]: {
            key: 'dateListed',
            title: 'Date Listed',
            inputType: InputType.DATE,
            isUrl: false,
            isDollarAmount: false,
            addSuffix: '',
            showColumn: true,
            isEditable: false,
            isSortable: true,
            detailedDescription: 'Date when the property was listed',
            routeTo: '',
        },
        [TableColumnEnum.DATE_CREATED]: {
            key: 'dateCreated',
            title: 'Date Created',
            inputType: InputType.DATE,
            isUrl: false,
            isDollarAmount: false,
            addSuffix: '',
            showColumn: true,
            isEditable: false,
            isSortable: true,
            detailedDescription: 'Date when this entry was created',
            routeTo: '',
        },
        [TableColumnEnum.CITY]: {
            key: 'city',
            title: 'City',
            inputType: InputType.TEXT,
            isUrl: false,
            isDollarAmount: false,
            addSuffix: '',
            showColumn: true,
            isEditable: true,
            isSortable: true,
            detailedDescription: 'City where the property is located',
            routeTo: '',
        },
        [TableColumnEnum.COUNTY]: {
            key: 'county',
            title: 'County',
            inputType: InputType.TEXT,
            isUrl: false,
            isDollarAmount: false,
            addSuffix: '',
            showColumn: true,
            isEditable: true,
            isSortable: true,
            detailedDescription: 'County where the property is located',
            routeTo: '',
        },
        [TableColumnEnum.COUNTRY]: {
            key: 'country',
            title: 'Country',
            inputType: InputType.SELECT,
            isUrl: false,
            isDollarAmount: false,
            addSuffix: '',
            showColumn: true,
            isEditable: true,
            isSortable: true,
            detailedDescription: 'Country where the property is located',
            routeTo: '',
        },
        [TableColumnEnum.STREET_ADDRESS]: {
            key: 'streetAddress',
            title: 'Street Address',
            inputType: InputType.TEXT,
            isUrl: false,
            isDollarAmount: false,
            addSuffix: '',
            showColumn: true,
            isEditable: true,
            isSortable: true,
            detailedDescription: 'Street address of the property',
            routeTo: '',
        },
        [TableColumnEnum.APARTMENT_NUMBER]: {
            key: 'apartmentNumber',
            title: 'Apt/Unit #',
            inputType: InputType.TEXT,
            isUrl: false,
            isDollarAmount: false,
            addSuffix: '',
            showColumn: true,
            isEditable: true,
            isSortable: true,
            detailedDescription: 'Apartment or unit number',
            routeTo: '',
        },
        [TableColumnEnum.LONGITUDE]: {
            key: 'longitude',
            title: 'Longitude',
            inputType: InputType.NUMBER,
            isUrl: false,
            isDollarAmount: false,
            addSuffix: '°',
            showColumn: false,
            isEditable: true,
            isSortable: false,
            detailedDescription: 'Longitude coordinate of the property',
            routeTo: '',
        },
        [TableColumnEnum.LATITUDE]: {
            key: 'latitude',
            title: 'Latitude',
            inputType: InputType.NUMBER,
            isUrl: false,
            isDollarAmount: false,
            addSuffix: '°',
            showColumn: false,
            isEditable: true,
            isSortable: false,
            detailedDescription: 'Latitude coordinate of the property',
            routeTo: '',
        },
        [TableColumnEnum.ELEMENTARY_SCHOOL_RATING]: {
            key: 'elementarySchoolRating',
            title: 'Elementary School',
            inputType: InputType.RATING,
            isUrl: false,
            isDollarAmount: false,
            addSuffix: '/10',
            showColumn: true,
            isEditable: true,
            isSortable: true,
            detailedDescription: 'Rating of nearby elementary school',
            routeTo: '',
        },
        [TableColumnEnum.MIDDLE_SCHOOL_RATING]: {
            key: 'middleSchoolRating',
            title: 'Middle School',
            inputType: InputType.RATING,
            isUrl: false,
            isDollarAmount: false,
            addSuffix: '/10',
            showColumn: true,
            isEditable: true,
            isSortable: true,
            detailedDescription: 'Rating of nearby middle school',
            routeTo: '',
        },
        [TableColumnEnum.HIGH_SCHOOL_RATING]: {
            key: 'highSchoolRating',
            title: 'High School',
            inputType: InputType.RATING,
            isUrl: false,
            isDollarAmount: false,
            addSuffix: '/10',
            showColumn: true,
            isEditable: true,
            isSortable: true,
            detailedDescription: 'Rating of nearby high school',
            routeTo: '',
        },
        [TableColumnEnum.NUMBER_OF_BEDROOMS]: {
            key: 'bedrooms',
            title: 'Beds',
            inputType: InputType.NUMBER,
            isUrl: false,
            isDollarAmount: false,
            addSuffix: '',
            showColumn: true,
            isEditable: true,
            isSortable: true,
            detailedDescription: 'Number of bedrooms',
            routeTo: '',
        },
        [TableColumnEnum.NUMBER_OF_FULL_BATHROOMS]: {
            key: 'fullBathrooms',
            title: 'Full Baths',
            inputType: InputType.NUMBER,
            isUrl: false,
            isDollarAmount: false,
            addSuffix: '',
            showColumn: true,
            isEditable: true,
            isSortable: true,
            detailedDescription: 'Number of full bathrooms',
            routeTo: '',
        },
        [TableColumnEnum.NUMBER_OF_HALF_BATHROOMS]: {
            key: 'halfBathrooms',
            title: 'Half Baths',
            inputType: InputType.NUMBER,
            isUrl: false,
            isDollarAmount: false,
            addSuffix: '',
            showColumn: true,
            isEditable: true,
            isSortable: true,
            detailedDescription: 'Number of half bathrooms',
            routeTo: '',
        },
        [TableColumnEnum.SQUARE_FEET]: {
            key: 'squareFeet',
            title: 'Square Feet',
            inputType: InputType.NUMBER,
            isUrl: false,
            isDollarAmount: false,
            addSuffix: ' sq ft',
            showColumn: true,
            isEditable: true,
            isSortable: true,
            detailedDescription: 'Property size in square feet',
            routeTo: '',
        },
        [TableColumnEnum.ACRES]: {
            key: 'acres',
            title: 'Lot Size',
            inputType: InputType.NUMBER,
            isUrl: false,
            isDollarAmount: false,
            addSuffix: ' acres',
            showColumn: true,
            isEditable: true,
            isSortable: true,
            detailedDescription: 'Lot size in acres',
            routeTo: '',
        },
        [TableColumnEnum.YEAR_BUILT]: {
            key: 'yearBuilt',
            title: 'Year Built',
            inputType: InputType.NUMBER,
            isUrl: false,
            isDollarAmount: false,
            addSuffix: '',
            showColumn: true,
            isEditable: true,
            isSortable: true,
            detailedDescription: 'Year the property was built',
            routeTo: '',
        },
        [TableColumnEnum.HAS_GARAGE]: {
            key: 'hasGarage',
            title: 'Garage',
            inputType: InputType.CHECKBOX,
            isUrl: false,
            isDollarAmount: false,
            addSuffix: '',
            showColumn: true,
            isEditable: true,
            isSortable: true,
            detailedDescription: 'Property has a garage',
            routeTo: '',
        },
        [TableColumnEnum.HAS_POOL]: {
            key: 'hasPool',
            title: 'Pool',
            inputType: InputType.CHECKBOX,
            isUrl: false,
            isDollarAmount: false,
            addSuffix: '',
            showColumn: true,
            isEditable: true,
            isSortable: true,
            detailedDescription: 'Property has a pool',
            routeTo: '',
        },
        [TableColumnEnum.HAS_BASEMENT]: {
            key: 'hasBasement',
            title: 'Basement',
            inputType: InputType.CHECKBOX,
            isUrl: false,
            isDollarAmount: false,
            addSuffix: '',
            showColumn: true,
            isEditable: true,
            isSortable: true,
            detailedDescription: 'Property has a basement',
            routeTo: '',
        },
        [TableColumnEnum.LISTING_PRICE]: {
            key: 'listingPrice',
            title: 'Listing Price',
            inputType: InputType.MONEY,
            isUrl: false,
            isDollarAmount: true,
            addSuffix: '',
            showColumn: true,
            isEditable: true,
            isSortable: true,
            detailedDescription: 'Price the property is listed for',
            routeTo: '',
        },
        [TableColumnEnum.ZESTIMATE]: {
            key: 'zestimate',
            title: 'Zestimate',
            inputType: InputType.MONEY,
            isUrl: false,
            isDollarAmount: true,
            addSuffix: '',
            showColumn: true,
            isEditable: false,
            isSortable: true,
            detailedDescription: 'Zillow estimated value of the property',
            routeTo: '',
        },
        [TableColumnEnum.ZILLOW_RENT_ESTIMATE]: {
            key: 'zillowRentEstimate',
            title: 'Zillow Rent Est.',
            inputType: InputType.MONEY,
            isUrl: false,
            isDollarAmount: true,
            addSuffix: '/mo',
            showColumn: true,
            isEditable: false,
            isSortable: true,
            detailedDescription: 'Zillow estimated monthly rent',
            routeTo: '',
        },
        [TableColumnEnum.ZESTIMATE_RANGE_LOW]: {
            key: 'zestimateLow',
            title: 'Zestimate Low',
            inputType: InputType.MONEY,
            isUrl: false,
            isDollarAmount: true,
            addSuffix: '',
            showColumn: false,
            isEditable: false,
            isSortable: true,
            detailedDescription: 'Lower range of Zillow estimated value',
            routeTo: '',
        },
        [TableColumnEnum.ZESTIMATE_RANGE_HIGH]: {
            key: 'zestimateHigh',
            title: 'Zestimate High',
            inputType: InputType.MONEY,
            isUrl: false,
            isDollarAmount: true,
            addSuffix: '',
            showColumn: false,
            isEditable: false,
            isSortable: true,
            detailedDescription: 'Upper range of Zillow estimated value',
            routeTo: '',
        },
        [TableColumnEnum.ZILLOW_MONTHLY_PROPERTY_TAX_AMOUNT]: {
            key: 'zillowPropertyTax',
            title: 'Property Tax (Zillow)',
            inputType: InputType.MONEY,
            isUrl: false,
            isDollarAmount: true,
            addSuffix: '/mo',
            showColumn: true,
            isEditable: false,
            isSortable: true,
            detailedDescription: 'Monthly property tax amount according to Zillow',
            routeTo: '',
        },
        [TableColumnEnum.ZILLOW_MONTHLY_HOME_INSURANCE_AMOUNT]: {
            key: 'zillowInsurance',
            title: 'Insurance (Zillow)',
            inputType: InputType.MONEY,
            isUrl: false,
            isDollarAmount: true,
            addSuffix: '/mo',
            showColumn: true,
            isEditable: false,
            isSortable: true,
            detailedDescription: 'Monthly home insurance amount according to Zillow',
            routeTo: '',
        },
        [TableColumnEnum.ZILLOW_MONTHLY_HOA_FEES_AMOUNT]: {
            key: 'zillowHOA',
            title: 'HOA Fees (Zillow)',
            inputType: InputType.MONEY,
            isUrl: false,
            isDollarAmount: true,
            addSuffix: '/mo',
            showColumn: true,
            isEditable: false,
            isSortable: true,
            detailedDescription: 'Monthly HOA fees according to Zillow',
            routeTo: '',
        },
        [TableColumnEnum.CREATION_TYPE]: {
            key: 'creationType',
            title: 'Creation Type',
            inputType: InputType.SELECT,
            isUrl: false,
            isDollarAmount: false,
            addSuffix: '',
            showColumn: false,
            isEditable: false,
            isSortable: true,
            detailedDescription: 'How the property entry was created (Manual, Import, API)',
            routeTo: '',
        },
        [TableColumnEnum.DESCRIPTION]: {
            key: 'description',
            title: 'Description',
            inputType: InputType.TEXTAREA,
            isUrl: false,
            isDollarAmount: false,
            addSuffix: '',
            showColumn: false,
            isEditable: true,
            isSortable: false,
            detailedDescription: 'Property description',
            routeTo: '',
        },
        [TableColumnEnum.INVESTMENT_BREAKDOWN_COLUMN]: {
            key: 'investmentBreakdown',
            title: 'Investment Breakdown',
            inputType: InputType.DISPLAY,
            isUrl: false,
            isDollarAmount: false,
            addSuffix: '',
            showColumn: true,
            isEditable: false,
            isSortable: false,
            detailedDescription: 'Breakdown of investment metrics',
            routeTo: '/investment-breakdown',
        },
        [TableColumnEnum.YEAR]: {
            key: 'year',
            title: 'Year',
            inputType: InputType.NUMBER,
            isUrl: false,
            isDollarAmount: false,
            addSuffix: '',
            showColumn: true,
            isEditable: false,
            isSortable: true,
            detailedDescription: 'Year for the financial data',
            routeTo: '',
        },
        [TableColumnEnum.MONTH]: {
            key: 'month',
            title: 'Month',
            inputType: InputType.SELECT,
            isUrl: false,
            isDollarAmount: false,
            addSuffix: '',
            showColumn: true,
            isEditable: false,
            isSortable: true,
            detailedDescription: 'Month for the financial data',
            routeTo: '',
        },
        [TableColumnEnum.DATE]: {
            key: 'date',
            title: 'Date',
            inputType: InputType.DATE,
            isUrl: false,
            isDollarAmount: false,
            addSuffix: '',
            showColumn: true,
            isEditable: false,
            isSortable: true,
            detailedDescription: 'Date for the financial data',
            routeTo: '',
        },
        [TableColumnEnum.TOTAL_INTEREST_PAID]: {
            key: 'totalInterestPaid',
            title: 'Total Interest Paid',
            inputType: InputType.MONEY,
            isUrl: false,
            isDollarAmount: true,
            addSuffix: '',
            showColumn: true,
            isEditable: false,
            isSortable: true,
            detailedDescription: 'Total interest paid to date',
            routeTo: '',
        },
        [TableColumnEnum.TOTAL_PRINCIPAL_PAID]: {
            key: 'totalPrincipalPaid',
            title: 'Total Principal Paid',
            inputType: InputType.MONEY,
            isUrl: false,
            isDollarAmount: true,
            addSuffix: '',
            showColumn: true,
            isEditable: false,
            isSortable: true,
            detailedDescription: 'Total principal paid to date',
            routeTo: '',
        },
        [TableColumnEnum.REMAINING_BALANCE]: {
            key: 'remainingBalance',
            title: 'Remaining Balance',
            inputType: InputType.MONEY,
            isUrl: false,
            isDollarAmount: true,
            addSuffix: '',
            showColumn: true,
            isEditable: false,
            isSortable: true,
            detailedDescription: 'Remaining loan balance',
            routeTo: '',
        },
        [TableColumnEnum.MONTHLY_INCOME]: {
            key: 'monthlyIncome',
            title: 'Monthly Income',
            inputType: InputType.MONEY,
            isUrl: false,
            isDollarAmount: true,
            addSuffix: '/mo',
            showColumn: true,
            isEditable: true,
            isSortable: true,
            detailedDescription: 'Total monthly income from the property',
            routeTo: '',
        },
        [TableColumnEnum.MONTHLY_EXPENSES]: {
            key: 'monthlyExpenses',
            title: 'Monthly Expenses',
            inputType: InputType.MONEY,
            isUrl: false,
            isDollarAmount: true,
            addSuffix: '/mo',
            showColumn: true,
            isEditable: true,
            isSortable: true,
            detailedDescription: 'Total monthly expenses for the property',
            routeTo: '',
        },
        [TableColumnEnum.ACCUMULATED_CASH_FLOW]: {
            key: 'accumulatedCashFlow',
            title: 'Accumulated Cash Flow',
            inputType: InputType.MONEY,
            isUrl: false,
            isDollarAmount: true,
            addSuffix: '',
            showColumn: true,
            isEditable: false,
            isSortable: true,
            detailedDescription: 'Total cash flow accumulated to date',
            routeTo: '',
        },
        [TableColumnEnum.APPRECIATION_AMOUNT]: {
            key: 'appreciationAmount',
            title: 'Appreciation',
            inputType: InputType.MONEY,
            isUrl: false,
            isDollarAmount: true,
            addSuffix: '',
            showColumn: true,
            isEditable: false,
            isSortable: true,
            detailedDescription: 'Amount the property has appreciated',
            routeTo: '',
        },
        [TableColumnEnum.PMI_AMOUNT]: {
            key: 'pmiAmount',
            title: 'PMI',
            inputType: InputType.MONEY,
            isUrl: false,
            isDollarAmount: true,
            addSuffix: '/mo',
            showColumn: true,
            isEditable: true,
            isSortable: true,
            detailedDescription: 'Private Mortgage Insurance monthly amount',
            routeTo: '',
        },
        [TableColumnEnum.INTEREST_PAYMENT]: {
            key: 'interestPayment',
            title: 'Interest Payment',
            inputType: InputType.MONEY,
            isUrl: false,
            isDollarAmount: true,
            addSuffix: '/mo',
            showColumn: true,
            isEditable: false,
            isSortable: true,
            detailedDescription: 'Monthly interest payment portion',
            routeTo: '',
        },
        [TableColumnEnum.PRINCIPAL_PAYMENT]: {
            key: 'principalPayment',
            title: 'Principal Payment',
            inputType: InputType.MONEY,
            isUrl: false,
            isDollarAmount: true,
            addSuffix: '/mo',
            showColumn: true,
            isEditable: false,
            isSortable: true,
            detailedDescription: 'Monthly principal payment portion',
            routeTo: '',
        },
        [TableColumnEnum.PERCENTAGE_OF_INTEREST]: {
            key: 'percentageOfInterest',
            title: 'Interest %',
            inputType: InputType.PERCENTAGE,
            isUrl: false,
            isDollarAmount: false,
            addSuffix: '%',
            showColumn: true,
            isEditable: false,
            isSortable: true,
            detailedDescription: 'Percentage of payment that is interest',
            routeTo: '',
        },
        [TableColumnEnum.PERCENTAGE_OF_PRINCIPAL]: {
            key: 'percentageOfPrincipal',
            title: 'Principal %',
            inputType: InputType.PERCENTAGE,
            isUrl: false,
            isDollarAmount: false,
            addSuffix: '%',
            showColumn: true,
            isEditable: false,
            isSortable: true,
            detailedDescription: 'Percentage of payment that is principal',
            routeTo: '',
        },
        [TableColumnEnum.EQUITY_AMOUNT]: {
            key: 'equityAmount',
            title: 'Equity',
            inputType: InputType.MONEY,
            isUrl: false,
            isDollarAmount: true,
            addSuffix: '',
            showColumn: true,
            isEditable: false,
            isSortable: true,
            detailedDescription: 'Current equity in the property',
            routeTo: '',
        },
        [TableColumnEnum.NET_OPERATING_INCOME]: {
            key: 'netOperatingIncome',
            title: 'NOI',
            inputType: InputType.MONEY,
            isUrl: false,
            isDollarAmount: true,
            addSuffix: '/yr',
            showColumn: true,
            isEditable: false,
            isSortable: true,
            detailedDescription: 'Net Operating Income (income minus expenses before mortgage)',
            routeTo: '/noi-details',
        },
        [TableColumnEnum.ACCUMULATED_NET_OPERATING_INCOME]: {
            key: 'accumulatedNOI',
            title: 'Accumulated NOI',
            inputType: InputType.MONEY,
            isUrl: false,
            isDollarAmount: true,
            addSuffix: '',
            showColumn: true,
            isEditable: false,
            isSortable: true,
            detailedDescription: 'Total Net Operating Income accumulated to date',
            routeTo: '',
        },
        [TableColumnEnum.CASH_ON_CASH_RETURN]: {
            key: 'cashOnCashReturn',
            title: 'CoC Return',
            inputType: InputType.PERCENTAGE,
            isUrl: false,
            isDollarAmount: false,
            addSuffix: '%',
            showColumn: true,
            isEditable: false,
            isSortable: true,
            detailedDescription: 'Annual cash flow divided by total cash invested',
            routeTo: '/coc-details',
        },
        [TableColumnEnum.MONTHLY_NET_INCOME]: {
            key: 'monthlyNetIncome',
            title: 'Monthly Net Income',
            inputType: InputType.MONEY,
            isUrl: false,
            isDollarAmount: true,
            addSuffix: '/mo',
            showColumn: true,
            isEditable: false,
            isSortable: true,
            detailedDescription: 'Monthly income after all expenses (including mortgage)',
            routeTo: '',
        },
        [TableColumnEnum.ACCUMULATED_NET_INCOME]: {
            key: 'accumulatedNetIncome',
            title: 'Accumulated Net Income',
            inputType: InputType.MONEY,
            isUrl: false,
            isDollarAmount: true,
            addSuffix: '',
            showColumn: true,
            isEditable: false,
            isSortable: true,
            detailedDescription: 'Total net income accumulated to date',
            routeTo: '',
        },
        [TableColumnEnum.PROPERTY_MANAGEMENT_AMOUNT]: {
            key: 'propertyManagementAmount',
            title: 'Property Management',
            inputType: InputType.MONEY,
            isUrl: false,
            isDollarAmount: true,
            addSuffix: '/mo',
            showColumn: true,
            isEditable: true,
            isSortable: true,
            detailedDescription: 'Monthly property management fee',
            routeTo: '',
        },
        [TableColumnEnum.VACANCY_AMOUNT]: {
            key: 'vacancyAmount',
            title: 'Vacancy Reserve',
            inputType: InputType.MONEY,
            isUrl: false,
            isDollarAmount: true,
            addSuffix: '/mo',
            showColumn: true,
            isEditable: true,
            isSortable: true,
            detailedDescription: 'Monthly amount set aside for vacancy periods',
            routeTo: '',
        },
        [TableColumnEnum.MAINTENANCE_AMOUNT]: {
            key: 'maintenanceAmount',
            title: 'Maintenance',
            inputType: InputType.MONEY,
            isUrl: false,
            isDollarAmount: true,
            addSuffix: '/mo',
            showColumn: true,
            isEditable: true,
            isSortable: true,
            detailedDescription: 'Monthly amount for regular maintenance',
            routeTo: '',
        },
        [TableColumnEnum.CAP_EX_RESERVE_AMOUNT]: {
            key: 'capExReserveAmount',
            title: 'CapEx Reserve',
            inputType: InputType.MONEY,
            isUrl: false,
            isDollarAmount: true,
            addSuffix: '/mo',
            showColumn: true,
            isEditable: true,
            isSortable: true,
            detailedDescription: 'Monthly amount set aside for major repairs and replacements',
            routeTo: '',
        },
        [TableColumnEnum.OTHER_EXPENSE_AMOUNT]: {
            key: 'otherExpenseAmount',
            title: 'Other Expenses',
            inputType: InputType.MONEY,
            isUrl: false,
            isDollarAmount: true,
            addSuffix: '/mo',
            showColumn: true,
            isEditable: true,
            isSortable: true,
            detailedDescription: 'Monthly miscellaneous expenses',
            routeTo: '',
        },
        [TableColumnEnum.OPERATIONAL_COSTS]: {
            key: 'operationalCosts',
            title: 'Operational Costs',
            inputType: InputType.MONEY,
            isUrl: false,
            isDollarAmount: true,
            addSuffix: '/mo',
            showColumn: true,
            isEditable: false,
            isSortable: true,
            detailedDescription: 'Total monthly operational expenses',
            routeTo: '/operational-cost-breakdown',
        },
        [TableColumnEnum.PROPERTY_TAX_AMOUNT]: {
            key: 'propertyTaxAmount',
            title: 'Property Tax',
            inputType: InputType.MONEY,
            isUrl: false,
            isDollarAmount: true,
            addSuffix: '/mo',
            showColumn: true,
            isEditable: true,
            isSortable: true,
            detailedDescription: 'Monthly property tax amount',
            routeTo: '',
        },
        [TableColumnEnum.MONTHLY_HOME_INSURANCE_AMOUNT]: {
            key: 'homeInsuranceAmount',
            title: 'Home Insurance',
            inputType: InputType.MONEY,
            isUrl: false,
            isDollarAmount: true,
            addSuffix: '/mo',
            showColumn: true,
            isEditable: true,
            isSortable: true,
            detailedDescription: 'Monthly home insurance cost',
            routeTo: '',
        },
        [TableColumnEnum.MONTHLY_HOA_FEES_AMOUNT]: {
            key: 'hoaFeesAmount',
            title: 'HOA Fees',
            inputType: InputType.MONEY,
            isUrl: false,
            isDollarAmount: true,
            addSuffix: '/mo',
            showColumn: true,
            isEditable: true,
            isSortable: true,
            detailedDescription: 'Monthly homeowners association fees',
            routeTo: '',
        },
        [TableColumnEnum.FIXED_COSTS]: {
            key: 'fixedCosts',
            title: 'Fixed Costs',
            inputType: InputType.MONEY,
            isUrl: false,
            isDollarAmount: true,
            addSuffix: '/mo',
            showColumn: true,
            isEditable: false,
            isSortable: true,
            detailedDescription: 'Total monthly fixed costs',
            routeTo: '/fixed-cost-breakdown',
        },
        [TableColumnEnum.MONTHLY_PAYMENT]: {
            key: 'monthlyPayment',
            title: 'Monthly Payment',
            inputType: InputType.MONEY,
            isUrl: false,
            isDollarAmount: true,
            addSuffix: '/mo',
            showColumn: true,
            isEditable: false,
            isSortable: true,
            detailedDescription: 'Total monthly mortgage payment',
            routeTo: '',
        },
        [TableColumnEnum.MONTHLY_PAYMENT_AND_OPERATIONAL_COSTS]: {
            key: 'totalMonthlyCosts',
            title: 'Total Monthly Costs',
            inputType: InputType.MONEY,
            isUrl: false,
            isDollarAmount: true,
            addSuffix: '/mo',
            showColumn: true,
            isEditable: false,
            isSortable: true,
            detailedDescription: 'Sum of mortgage payment and operational costs',
            routeTo: '',
        },
        [TableColumnEnum.FIRST_NAME]: {
            key: 'firstName',
            title: 'First Name',
            inputType: InputType.TEXT,
            isUrl: false,
            isDollarAmount: false,
            addSuffix: '',
            showColumn: true,
            isEditable: true,
            isSortable: true,
            detailedDescription: 'Contact\'s first name',
            routeTo: '',
        },
        [TableColumnEnum.LAST_NAME]: {
            key: 'lastName',
            title: 'Last Name',
            inputType: InputType.TEXT,
            isUrl: false,
            isDollarAmount: false,
            addSuffix: '',
            showColumn: true,
            isEditable: true,
            isSortable: true,
            detailedDescription: 'Contact\'s last name',
            routeTo: '',
        },
        [TableColumnEnum.FULL_NAME]: {
            key: 'fullName',
            title: 'Full Name',
            inputType: InputType.TEXT,
            isUrl: false,
            isDollarAmount: false,
            addSuffix: '',
            showColumn: true,
            isEditable: false,
            isSortable: true,
            detailedDescription: 'Contact\'s full name',
            routeTo: '/contact-details',
        },
        [TableColumnEnum.WEBSITE]: {
            key: 'website',
            title: 'Website',
            inputType: InputType.URL,
            isUrl: true,
            isDollarAmount: false,
            addSuffix: '',
            showColumn: true,
            isEditable: true,
            isSortable: true,
            detailedDescription: 'Contact\'s website URL',
            routeTo: '',
        },
        [TableColumnEnum.COMPANY_NAME]: {
            key: 'companyName',
            title: 'Company',
            inputType: InputType.TEXT,
            isUrl: false,
            isDollarAmount: false,
            addSuffix: '',
            showColumn: true,
            isEditable: true,
            isSortable: true,
            detailedDescription: 'Contact\'s company name',
            routeTo: '',
        },
        [TableColumnEnum.PHONE_NUMBER]: {
            key: 'phoneNumber',
            title: 'Phone',
            inputType: InputType.PHONE,
            isUrl: false,
            isDollarAmount: false,
            addSuffix: '',
            showColumn: true,
            isEditable: true,
            isSortable: true,
            detailedDescription: 'Contact\'s phone number',
            routeTo: '',
        },
        [TableColumnEnum.EMAIL]: {
            key: 'email',
            title: 'Email',
            inputType: InputType.EMAIL,
            isUrl: false,
            isDollarAmount: false,
            addSuffix: '',
            showColumn: true,
            isEditable: true,
            isSortable: true,
            detailedDescription: 'Contact\'s email address',
            routeTo: '',
        },
        [TableColumnEnum.AGENT_TYPE]: {
            key: 'agentType',
            title: 'Agent Type',
            inputType: InputType.SELECT,
            isUrl: false,
            isDollarAmount: false,
            addSuffix: '',
            showColumn: true,
            isEditable: true,
            isSortable: true,
            detailedDescription: 'Type of agent (Buyer\'s Agent, Listing Agent, etc.)',
            routeTo: '',
        },
        [TableColumnEnum.START_PRINCIPAL]: {
            key: 'startPrincipal',
            title: 'Starting Principal',
            inputType: InputType.MONEY,
            isUrl: false,
            isDollarAmount: true,
            addSuffix: '',
            showColumn: true,
            isEditable: false,
            isSortable: true,
            detailedDescription: 'Initial principal amount',
            routeTo: '',
        },
        [TableColumnEnum.START_BALANCE]: {
            key: 'startBalance',
            title: 'Starting Balance',
            inputType: InputType.MONEY,
            isUrl: false,
            isDollarAmount: true,
            addSuffix: '',
            showColumn: true,
            isEditable: false,
            isSortable: true,
            detailedDescription: 'Starting loan balance',
            routeTo: '',
        },
        [TableColumnEnum.INTEREST]: {
            key: 'interest',
            title: 'Interest',
            inputType: InputType.MONEY,
            isUrl: false,
            isDollarAmount: true,
            addSuffix: '',
            showColumn: true,
            isEditable: false,
            isSortable: true,
            detailedDescription: 'Interest amount for the period',
            routeTo: '',
        },
        [TableColumnEnum.ACCUMULATED_INTEREST]: {
            key: 'accumulatedInterest',
            title: 'Accumulated Interest',
            inputType: InputType.MONEY,
            isUrl: false,
            isDollarAmount: true,
            addSuffix: '',
            showColumn: true,
            isEditable: false,
            isSortable: true,
            detailedDescription: 'Total interest paid to date',
            routeTo: '',
        },
        [TableColumnEnum.END_BALANCE]: {
            key: 'endBalance',
            title: 'Ending Balance',
            inputType: InputType.MONEY,
            isUrl: false,
            isDollarAmount: true,
            addSuffix: '',
            showColumn: true,
            isEditable: false,
            isSortable: true,
            detailedDescription: 'Loan balance at the end of the period',
            routeTo: '',
        },
        [TableColumnEnum.END_PRINCIPAL]: {
            key: 'endPrincipal',
            title: 'Ending Principal',
            inputType: InputType.MONEY,
            isUrl: false,
            isDollarAmount: true,
            addSuffix: '',
            showColumn: true,
            isEditable: false,
            isSortable: true,
            detailedDescription: 'Principal amount at the end of the period',
            routeTo: '',
        },
        [TableColumnEnum.API_KEY_NAME]: {
            key: 'apiKeyName',
            title: 'API Key Name',
            inputType: InputType.TEXT,
            isUrl: false,
            isDollarAmount: false,
            addSuffix: '',
            showColumn: true,
            isEditable: true,
            isSortable: true,
            detailedDescription: 'Name of the API key',
            routeTo: '',
        },
        [TableColumnEnum.CAN_MAKE_API_CALL]: {
            key: 'canMakeApiCall',
            title: 'API Access',
            inputType: InputType.CHECKBOX,
            isUrl: false,
            isDollarAmount: false,
            addSuffix: '',
            showColumn: true,
            isEditable: false,
            isSortable: true,
            detailedDescription: 'Whether API calls can be made',
            routeTo: '',
        },
        [TableColumnEnum.API_CALLS_MAKE_THIS_MONTH]: {
            key: 'apiCallsThisMonth',
            title: 'API Calls This Month',
            inputType: InputType.NUMBER,
            isUrl: false,
            isDollarAmount: false,
            addSuffix: ' calls',
            showColumn: true,
            isEditable: false,
            isSortable: true,
            detailedDescription: 'Number of API calls made this month',
            routeTo: '',
        },
        [TableColumnEnum.REMAINING_NUMBER_OF_FREE_API_CALLS]: {
            key: 'remainingFreeApiCalls',
            title: 'Remaining Free Calls',
            inputType: InputType.NUMBER,
            isUrl: false,
            isDollarAmount: false,
            addSuffix: ' calls',
            showColumn: true,
            isEditable: false,
            isSortable: true,
            detailedDescription: 'Number of free API calls remaining',
            routeTo: '',
        },
        [TableColumnEnum.DAYS_INTO_BILLING_PERIOD]: {
            key: 'daysIntoBillingPeriod',
            title: 'Days into Billing',
            inputType: InputType.NUMBER,
            isUrl: false,
            isDollarAmount: false,
            addSuffix: ' days',
            showColumn: true,
            isEditable: false,
            isSortable: true,
            detailedDescription: 'Number of days into the current billing period',
            routeTo: '',
        },
        [TableColumnEnum.BILLING_PERIOD]: {
            key: 'billingPeriod',
            title: 'Billing Period',
            inputType: InputType.TEXT,
            isUrl: false,
            isDollarAmount: false,
            addSuffix: '',
            showColumn: true,
            isEditable: false,
            isSortable: true,
            detailedDescription: 'Current billing period',
            routeTo: '',
        },
        [TableColumnEnum.MOST_RECENT_BILLING_DATE]: {
            key: 'mostRecentBillingDate',
            title: 'Last Billed',
            inputType: InputType.DATE,
            isUrl: false,
            isDollarAmount: false,
            addSuffix: '',
            showColumn: true,
            isEditable: false,
            isSortable: true,
            detailedDescription: 'Date of the most recent billing',
            routeTo: '',
        },
        [TableColumnEnum.FIRST_BILLED_ON]: {
            key: 'firstBilledOn',
            title: 'First Billed',
            inputType: InputType.DATE,
            isUrl: false,
            isDollarAmount: false,
            addSuffix: '',
            showColumn: true,
            isEditable: false,
            isSortable: true,
            detailedDescription: 'Date when first billed',
            routeTo: '',
        },
    };

    createBasicColumn(column: TableColumnEnum, _accessor: (item: T) => TableCellValue): BasicColumn<T> {
        const colDetails = this.columnDetails[column];
        return new BasicColumn({
            key: colDetails.key,
            title: colDetails.title,
            accessor: _accessor,
            inputType: colDetails.inputType,
            isUrl: colDetails.isUrl,
            isDollarAmount: colDetails.isDollarAmount,
            addSuffix: colDetails.addSuffix,
            showColumn: colDetails.showColumn,
            isEditable: colDetails.isEditable,
            isSortable: colDetails.isSortable,
            detailedDescription: colDetails.detailedDescription,
        });
    }

}