import { TableColumn, TableDataItem, TableRow } from "../components/ReusableTable";
import {
    ListingWithScenariosResponseDTO,
} from "@realestatemanager/shared";
import {
    getAcres,
    getAnnualInterestRate,
    getApartmentNumber,
    getCapRate,
    getCity,
    getCountry,
    getCounty,
    getCreationType,
    getDateCreated,
    getDateListed,
    getDescription,
    getDownPaymentAmount,
    getElementarySchoolRating,
    getFullAddress,
    getHighSchoolRating,
    getInitialCosts,
    getInitialMonthlyAmount,
    getLatitude,
    getListingPrice,
    getLoanAmount,
    getLongitude,
    getMiddleSchoolRating,
    getMonthlyCashFlow,
    getMortgage,
    getNumberOfBedrooms,
    getNumberOfDaysOnMarket,
    getNumberOfFullBathrooms,
    getNumberOfHalfBathrooms,
    getPrice,
    getPropertyType,
    getROI,
    getRecurringCosts,
    getRentEstimate,
    getSquareFeet,
    getState,
    getStreetAddress,
    getYearBuilt,
    getYearlyCashFlow,
    getZestimate,
    getZestimateRangeHigh,
    getZestimateRangeLow,
    getZillowMonthlyHOAFeesAmount,
    getZillowMonthlyHomeInsuranceAmount,
    getZillowMonthlyPropertyTaxAmount,
    getZillowRentEstimate,
    getZillowURL,
    getZipCode,
    hasBasement,
    hasGarage,
    hasPool
} from "../components/TableColumn";
import { TablesConfig } from "../pages/InvestmentBreakdown";


export abstract class AbstractTable<T, X> {

    abstract getTableData(
        properties: ListingWithScenariosResponseDTO[],
        tableType: T
    ): TableDataItem<X>[];

    abstract getTablesConfig(): TablesConfig<X>;

    getDefaultColumns(): TableColumn[] {
        return [
            {
                header: "Property Type",
                accessor: "propertyType",
                isURL: false,
                showColumn: true,
                isDollarAmount: false,
                isSortable: true,
            },
            {
                header: "Full Address",
                accessor: "fullAddress",
                isURL: false,
                showColumn: true,
                isDollarAmount: false,
                isSortable: true
            },
            {
                header: "State",
                accessor: "state",
                isURL: false,
                showColumn: true,
                isDollarAmount: false,
                isSortable: true,
            },
            {
                header: "Zip Code",
                accessor: "zipcode",
                isURL: false,
                showColumn: true,
                isDollarAmount: false,
                isSortable: true,
            },
            {
                header: "Zillow URL",
                accessor: "zillowURL",
                isURL: true,
                showColumn: true,
                isDollarAmount: false,
                isSortable: true,
            },
            {
                header: "Price",
                accessor: "price",
                isURL: false,
                showColumn: true,
                isDollarAmount: true,
                isSortable: true,
            },
            {
                header: "Rent Estimate",
                accessor: "rentEstimate",
                isURL: false,
                showColumn: true,
                isDollarAmount: true,
                isSortable: true,
            },
            {
                header: "Initial Costs",
                accessor: "initialCosts",
                isURL: false,
                showColumn: true,
                isDollarAmount: true,
                isSortable: true,
                detailedDescription: `downPaymentAmount + 
                        legalAndProfessionalFees + 
                        initialRepairCosts + 
                        travelingCosts + 
                        closingCosts + 
                        otherInitialExpenses`,
            },
            {
                header: "Loan Amount",
                accessor: "loanAmount",
                isURL: false,
                showColumn: true,
                isDollarAmount: true,
                isSortable: true,
            },
            {
                header: "Down Payment",
                accessor: "downPaymentAmount",
                isURL: false,
                showColumn: true,
                isDollarAmount: true,
                isSortable: true
            },
            {
                header: "Annual Interest Rate",
                accessor: "annualInterestRate",
                isURL: false,
                showColumn: true,
                isDollarAmount: false,
                addSuffix: '%',
                isSortable: true,
            },
            {
                header: "ROI",
                accessor: "ROI",
                isURL: false,
                showColumn: true,
                isDollarAmount: false,
                addSuffix: '%',
                isSortable: true,
            },
            {
                header: "Cap Rate",
                accessor: "capRate",
                isURL: false,
                showColumn: true,
                isDollarAmount: false,
                addSuffix: '%',
                isSortable: true,
            },
            {
                header: "Recurring Costs",
                accessor: "recurringCosts",
                isURL: false,
                showColumn: true,
                isDollarAmount: true,
                isSortable: true,
                detailedDescription: `propertyManagementAmount + 
                        vacancyAmount +
                        maintenanceAmount +
                        otherExpensesAmount +
                        capExReserveAmount`,
            },
            {
                header: "Monthly Payment",
                accessor: "initialMonthlyAmount",
                isURL: false,
                showColumn: true,
                isDollarAmount: true,
                isSortable: true,
                detailedDescription: ` Mortgage Amount +
                                Property Tax Amount +
                                Monthly Home Insurance Amount +
                                Monthly HOA Fees Amount`,
            },
            {
                header: "Mortgage Amount",
                accessor: "mortgage",
                isURL: false,
                showColumn: true,
                isDollarAmount: true,
                isSortable: true,
            },
            {
                header: "Monthly Cash Flow",
                accessor: "monthlyCashFlow",
                isURL: false,
                showColumn: true,
                isDollarAmount: true,
                isSortable: true,
            },
            {
                header: "Yearly Cash Flow",
                accessor: "yearlyCashFlow",
                isURL: false,
                showColumn: true,
                isDollarAmount: true,
                isSortable: true,
            },
            {
                header: "Number of Days On Market",
                accessor: "numberOfDaysOnMarket",
                isURL: false,
                showColumn: true,
                isDollarAmount: false,
                isSortable: true,
            },
            {
                header: "Date Listed",
                accessor: "dateListed",
                isURL: false,
                showColumn: true,
                isDollarAmount: false,
                isSortable: true,
            },
            {
                header: "Date Created",
                accessor: "dateCreated",
                isURL: false,
                showColumn: true,
                isDollarAmount: false,
                isSortable: true,
            },
            {
                header: "City",
                accessor: "city",
                isURL: false,
                showColumn: false,
                isDollarAmount: false,
                isSortable: true,
            },
            {
                header: "County",
                accessor: "county",
                isURL: false,
                showColumn: false,
                isDollarAmount: false,
                isSortable: true,
            },
            {
                header: "Country",
                accessor: "country",
                isURL: false,
                showColumn: false,
                isDollarAmount: false,
                isSortable: true,
            },
            {
                header: "Street Address",
                accessor: "streetAddress",
                isURL: false,
                showColumn: false,
                isDollarAmount: false,
                isSortable: true,
            },
            {
                header: "Apartment Number",
                accessor: "apartmentNumber",
                isURL: false,
                showColumn: false,
                isDollarAmount: false,
                isSortable: false,
            },
            {
                header: "Longitude",
                accessor: "longitude",
                isURL: false,
                showColumn: false,
                isDollarAmount: false,
                isSortable: false,
            },
            {
                header: "Latitude",
                accessor: "latitude",
                isURL: false,
                showColumn: false,
                isDollarAmount: false,
                isSortable: false,
            },
            {
                header: "Elementary School Rating",
                accessor: "elementarySchoolRating",
                isURL: false,
                showColumn: false,
                isDollarAmount: false,
                isSortable: true,
            },
            {
                header: "Middle School Rating",
                accessor: "middleSchoolRating",
                isURL: false,
                showColumn: false,
                isDollarAmount: false,
                isSortable: true,
            },
            {
                header: "High School Rating",
                accessor: "highSchoolRating",
                isURL: false,
                showColumn: false,
                isDollarAmount: false,
                isSortable: true,
            },
            {
                header: "Number Of Bedrooms",
                accessor: "numberOfBedrooms",
                isURL: false,
                showColumn: false,
                isDollarAmount: false,
                isSortable: true,
            },
            {
                header: "Number Of Full Bathrooms",
                accessor: "numberOfFullBathrooms",
                isURL: false,
                showColumn: false,
                isDollarAmount: false,
                isSortable: true,
            },
            {
                header: "Number Of Half Bathrooms",
                accessor: "numberOfHalfBathrooms",
                isURL: false,
                showColumn: false,
                isDollarAmount: false,
                isSortable: true,
            },
            {
                header: "Square Feet",
                accessor: "squareFeet",
                isURL: false,
                showColumn: false,
                isDollarAmount: false,
                isSortable: true,
            },
            {
                header: "Acres",
                accessor: "acres",
                isURL: false,
                showColumn: false,
                isDollarAmount: false,
                isSortable: true,
            },
            {
                header: "Year Built",
                accessor: "yearBuilt",
                isURL: false,
                showColumn: false,
                isDollarAmount: false,
                isSortable: true,
            },
            {
                header: "Has Garage",
                accessor: "hasGarage",
                isURL: false,
                showColumn: false,
                isDollarAmount: false,
                isSortable: true,
            },
            {
                header: "Has Pool",
                accessor: "hasPool",
                isURL: false,
                showColumn: false,
                isDollarAmount: false,
                isSortable: true,
            },
            {
                header: "Has Basement",
                accessor: "hasBasement",
                isURL: false,
                showColumn: false,
                isDollarAmount: false,
                isSortable: true,
            },
            {
                header: "Listing Price",
                accessor: "listingPrice",
                isURL: false,
                showColumn: false,
                isDollarAmount: false,
                isSortable: true
            },
            {
                header: "Zestimate",
                accessor: "zestimate",
                isURL: false,
                showColumn: false,
                isDollarAmount: true,
                isSortable: true,
            },
            {
                header: "Zillow Rent Estimate",
                accessor: "zillowRentEstimate",
                isURL: false,
                showColumn: false,
                isDollarAmount: true,
                isSortable: true,
            },
            {
                header: "Zillow Range Low",
                accessor: "zestimateRangeLow",
                isURL: false,
                showColumn: false,
                isDollarAmount: true,
                isSortable: true,
            },
            {
                header: "Zillow Range High",
                accessor: "zestimateRangeHigh",
                isURL: false,
                showColumn: false,
                isDollarAmount: true,
                isSortable: true,
            },
            {
                header: "Zillow Monthly Property Tax Amount",
                accessor: "zillowMonthlyPropertyTaxAmount",
                isURL: false,
                showColumn: false,
                isDollarAmount: true,
                isSortable: true,
            },
            {
                header: "Zillow Monthly Home Insurance Amount",
                accessor: "zillowMonthlyHomeInsuranceAmount",
                isURL: false,
                showColumn: false,
                isDollarAmount: true,
                isSortable: true,
            },
            {
                header: "Zillow Monthly HOA Fees Amount",
                accessor: "zillowMonthlyHOAFeesAmount",
                isURL: false,
                showColumn: false,
                isDollarAmount: true,
                isSortable: true,
            },
            {
                header: "Creation Type",
                accessor: "creationType",
                isURL: false,
                showColumn: false,
                isDollarAmount: false,
                isSortable: false,
            },
            {
                header: "Description",
                accessor: "description",
                isURL: false,
                showColumn: false,
                isDollarAmount: false,
                isSortable: false,
            },
        ];
    }

    getDefaultRowData(property: ListingWithScenariosResponseDTO): TableRow {
        return {
            propertyType: getPropertyType(property),
            fullAddress: getFullAddress(property),
            state: getState(property),
            zipcode: getZipCode(property),
            zillowURL: getZillowURL(property),
            price: getPrice(property),
            rentEstimate: getRentEstimate(property),
            initialCosts: getInitialCosts(property),
            loanAmount: getLoanAmount(property),
            downPaymentAmount: getDownPaymentAmount(property),
            annualInterestRate: getAnnualInterestRate(property),
            ROI: getROI(property),
            capRate: getCapRate(property),
            recurringCosts: getRecurringCosts(property),
            initialMonthlyAmount: getInitialMonthlyAmount(property),
            mortgage: getMortgage(property),
            monthlyCashFlow: getMonthlyCashFlow(property),
            yearlyCashFlow: getYearlyCashFlow(property),
            city: getCity(property),
            county: getCounty(property),
            country: getCountry(property),
            streetAddress: getStreetAddress(property),
            apartmentNumber: getApartmentNumber(property),
            longitude: getLongitude(property),
            latitude: getLatitude(property),
            numberOfDaysOnMarket: getNumberOfDaysOnMarket(property),
            dateListed: getDateListed(property),
            dateCreated: getDateCreated(property),
            elementarySchoolRating: getElementarySchoolRating(property),
            middleSchoolRating: getMiddleSchoolRating(property),
            highSchoolRating: getHighSchoolRating(property),
            numberOfBedrooms: getNumberOfBedrooms(property),
            numberOfFullBathrooms: getNumberOfFullBathrooms(property),
            numberOfHalfBathrooms: getNumberOfHalfBathrooms(property),
            squareFeet: getSquareFeet(property),
            acres: getAcres(property),
            yearBuilt: getYearBuilt(property),
            hasGarage: hasGarage(property),
            hasPool: hasPool(property),
            hasBasement: hasBasement(property),
            listingPrice: getListingPrice(property),
            zestimate: getZestimate(property),
            zillowRentEstimate: getZillowRentEstimate(property),
            zestimateRangeLow: getZestimateRangeLow(property),
            zestimateRangeHigh: getZestimateRangeHigh(property),
            zillowMonthlyPropertyTaxAmount: getZillowMonthlyPropertyTaxAmount(property),
            zillowMonthlyHomeInsuranceAmount: getZillowMonthlyHomeInsuranceAmount(property),
            zillowMonthlyHOAFeesAmount: getZillowMonthlyHOAFeesAmount(property),
            description: getDescription(property),
            creationType: getCreationType(property),
            investmentBreakdown: 'View',
        };
    }

}