import { FirstNameColumn, LastNameColumn, FullNameColumn, WebsiteColumn, CompanyNameColumn, PhoneNumberColumn, EmailColumn, AgentTypeColumn } from "../tablecolumns/AgentTypeColumns";
import { StartPrincipalColumn, StartBalanceColumn, InterestColumn, AccumulatedInterestColumn, EndBalanceColumn, EndPrincipalColumn } from "../tablecolumns/HighYieldSavingsColumns";
import { TotalInterestPaidColumn, TotalPrincipalPaidColumn, RemainingBalanceColumn, MonthlyIncomeColumn, MonthlyExpensesColumn, AccumulatedCashFlowColumn, AppreciationAmountColumn, PMIAmountColumn, InterestPaymentColumn, PrincipalPaymentColumn, PercentageOfInterestColumn, PercentageOfPrincipalColumn, EquityAmountColumn, NetOperatingIncomeColumn, AccumulatedNetOperatingIncomeColumn, CashOnCashReturnColumn, MonthlyNetIncomeColumn, AccumulatedNetIncomeColumn, PropertyManagementAmountColumn, VacancyAmountColumn, MaintenanceAmountColumn, CapExReserveAmountColumn, OtherExpenseAmountColumn, OperationalCostsColumn, PropertyTaxAmountColumn, MonthlyHomeInsuranceAmountColumn, MonthlyHOAFeesAmountColumn, FixedCostsColumn, MonthlyPaymentColumn, MonthlyPaymentAndOperationalCostsColumn } from "../tablecolumns/InvestmentBreakdownColumns";
import { AcresColumn, AnnualInterestRateColumn, ApartmentNumberColumn, CityColumn, CountyColumn, CreationTypeColumn, DateCreatedColumn, DateListedColumn, DescriptionColumn, DownPaymentAmountColumn, ElementarySchoolRatingColumn, FullAddressColumn, HasBasementColumn, HasGarageColumn, HasPoolColumn, HighSchoolRatingColumn, InitialCostsColumn, InitialMonthlyPaymentColumn, LatitudeColumn, ListingPriceColumn, LoanAmountColumn, LongitudeColumn, MiddleSchoolRatingColumn, NumberOfBedroomsColumn, NumberOfDaysOnMarketColumn, NumberOfFullBathroomsColumn, NumberOfHalfBathroomsColumn, PriceColumn, PropertyTypeColumn, RecurringCostsColumn, SquareFeetColumn, StreetAddressColumn, YearBuiltColumn, YearlyCashFlowColumn, ZestimateColumn, ZestimateRangeHighColumn, ZestimateRangeLowColumn, ZillowMonthlyHOAFeesAmountColumn, ZillowMonthlyHomeInsuranceAmountColumn, ZillowMonthlyPropertyTaxAmountColumn, ZillowRentEstimateColumn, ZillowUrlColumn, ZipCodeColumn } from "../tablecolumns/PropertyListColumns";
import { ApiKeyNameColumn, CanMakeApiCallColumn, ApiCallsMadeThisMonthColumn, RemainingNumberOfFreeApiCallsColumn, DaysIntoBillingPeriodColumn, BillingPeriodColumn, MostRecentBillingDateColumn, FirstBilledOnColumn } from "../tablecolumns/RentCastApiDetailsColumns";
import { StateColumn, RentEstimateColumn, ROIColumn, CapRateColumn, MortgageAmountColumn, MonthlyCashFlowColumn, CountryColumn, YearColumn, MonthColumn, DateColumn } from "../tablecolumns/SharedColumns";
import { ColumnsDetails } from "../types/ClientTypes";

export enum TableColumnDetailsEnum {
    // Property List Columns
    PROPERTY_TYPE = 'PROPERTY_TYPE',
    FULL_ADDRESS = 'FULL_ADDRESS',
    STATE = 'STATE',
    ZIP_CODE = 'ZIP_CODE',
    ZILLOW_URL = 'ZILLOW_URL',
    PRICE = 'PRICE',
    RENT_ESTIMATE = 'RENT_ESTIMATE',
    INITIAL_COSTS = 'INITIAL_COSTS',
    LOAN_AMOUNT = 'LOAN_AMOUNT',
    DOWN_PAYMENT_AMOUNT = 'DOWN_PAYMENT_AMOUNT',
    ANNUAL_INTEREST_RATE = 'ANNUAL_INTEREST_RATE',
    ROI = 'ROI',
    CAP_RATE = 'CAP_RATE',
    RECURRING_COSTS = 'RECURRING_COSTS',
    INITIAL_MONTHLY_AMOUNT = 'INITIAL_MONTHLY_AMOUNT',
    MORTGAGE = 'MORTGAGE',
    MONTHLY_CASH_FLOW = 'MONTHLY_CASH_FLOW',
    YEARLY_CASH_FLOW = 'YEARLY_CASH_FLOW',
    NUMBER_OF_DAYS_ON_MARKET = 'NUMBER_OF_DAYS_ON_MARKET',
    DATE_LISTED = 'DATE_LISTED',
    DATE_CREATED = 'DATE_CREATED',
    CITY = 'CITY',
    COUNTY = 'COUNTY',
    COUNTRY = 'COUNTRY',
    STREET_ADDRESS = 'STREET_ADDRESS',
    APARTMENT_NUMBER = 'APARTMENT_NUMBER',
    LONGITUDE = 'LONGITUDE',
    LATITUDE = 'LATITUDE',
    ELEMENTARY_SCHOOL_RATING = 'ELEMENTARY_SCHOOL_RATING',
    MIDDLE_SCHOOL_RATING = 'MIDDLE_SCHOOL_RATING',
    HIGH_SCHOOL_RATING = 'HIGH_SCHOOL_RATING',
    NUMBER_OF_BEDROOMS = 'NUMBER_OF_BEDROOMS',
    NUMBER_OF_FULL_BATHROOMS = 'NUMBER_OF_FULL_BATHROOMS',
    NUMBER_OF_HALF_BATHROOMS = 'NUMBER_OF_HALF_BATHROOMS',
    SQUARE_FEET = 'SQUARE_FEET',
    ACRES = 'ACRES',
    YEAR_BUILT = 'YEAR_BUILT',
    HAS_GARAGE = 'HAS_GARAGE',
    HAS_POOL = 'HAS_POOL',
    HAS_BASEMENT = 'HAS_BASEMENT',
    LISTING_PRICE = 'LISTING_PRICE',
    ZESTIMATE = 'ZESTIMATE',
    ZILLOW_RENT_ESTIMATE = 'ZILLOW_RENT_ESTIMATE',
    ZESTIMATE_RANGE_LOW = 'ZESTIMATE_RANGE_LOW',
    ZESTIMATE_RANGE_HIGH = 'ZESTIMATE_RANGE_HIGH',
    ZILLOW_MONTHLY_PROPERTY_TAX_AMOUNT = 'ZILLOW_MONTHLY_PROPERTY_TAX_AMOUNT',
    ZILLOW_MONTHLY_HOME_INSURANCE_AMOUNT = 'ZILLOW_MONTHLY_HOME_INSURANCE_AMOUNT',
    ZILLOW_MONTHLY_HOA_FEES_AMOUNT = 'ZILLOW_MONTHLY_HOA_FEES_AMOUNT',
    CREATION_TYPE = 'CREATION_TYPE',
    DESCRIPTION = 'DESCRIPTION',

    // InvestmentBreakdown Columns
    YEAR = 'YEAR',
    MONTH = 'MONTH',
    DATE = 'DATE',
    //MORTGAGE
    TOTAL_INTEREST_PAID = 'TOTAL_INTEREST_PAID',
    TOTAL_PRINCIPAL_PAID = 'TOTAL_PRINCIPAL_PAID',
    REMAINING_BALANCE = 'REMAINING_BALANCE',
    // RENT ESTIMATE
    MONTHLY_INCOME = 'MONTHLY_INCOME',
    MONTHLY_EXPENSES = 'MONTHLY_EXPENSES',
    // MONTHLY CASH FLOW
    ACCUMULATED_CASH_FLOW = 'ACCUMULATED_CASH_FLOW',
    APPRECIATION_AMOUNT = 'APPRECIATION_AMOUNT',
    PMI_AMOUNT = 'PMI_AMOUNT',
    INTEREST_PAYMENT = 'INTEREST_PAYMENT',
    PRINCIPAL_PAYMENT = 'PRINCIPAL_PAYMENT',
    PERCENTAGE_OF_INTEREST = 'PERCENTAGE_OF_INTEREST',
    PERCENTAGE_OF_PRINCIPAL = 'PERCENTAGE_OF_PRINCIPAL',
    EQUITY_AMOUNT = 'EQUITY_AMOUNT',
    NET_OPERATING_INCOME = 'NET_OPERATING_INCOME',
    ACCUMULATED_NET_OPERATING_INCOME = 'ACCUMULATED_NET_OPERATING_INCOME',
    CASH_ON_CASH_RETURN = 'CASH_ON_CASH_RETURN',
    MONTHLY_NET_INCOME = 'MONTHLY_NET_INCOME',
    ACCUMULATED_NET_INCOME = 'ACCUMULATED_NET_INCOME',
    PROPERTY_MANAGEMENT_AMOUNT = 'PROPERTY_MANAGEMENT_AMOUNT',
    VACANCY_AMOUNT = 'VACANCY_AMOUNT',
    MAINTENANCE_AMOUNT = 'MAINTENANCE_AMOUNT',
    CAP_EX_RESERVE_AMOUNT = 'CAP_EX_RESERVE_AMOUNT',
    OTHER_EXPENSE_AMOUNT = 'OTHER_EXPENSE_AMOUNT',
    OPERATIONAL_COSTS = 'OPERATIONAL_COSTS',
    PROPERTY_TAX_AMOUNT = 'PROPERTY_TAX_AMOUNT',
    MONTHLY_HOME_INSURANCE_AMOUNT = 'MONTHLY_HOME_INSURANCE_AMOUNT',
    MONTHLY_HOA_FEES_AMOUNT = 'MONTHLY_HOA_FEES_AMOUNT',
    FIXED_COSTS = 'FIXED_COSTS',
    MONTHLY_PAYMENT = 'MONTHLY_PAYMENT',
    MONTHLY_PAYMENT_AND_OPERATIONAL_COSTS = 'MONTHLY_PAYMENT_AND_OPERATIONAL_COSTS',

    // Agent 
    FIRST_NAME = 'FIRST_NAME',
    LAST_NAME = 'LAST_NAME',
    FULL_NAME = 'FULL_NAME',
    WEBSITE = 'WEBSITE',
    COMPANY_NAME = 'COMPANY_NAME',
    PHONE_NUMBER = 'PHONE_NUMBER',
    EMAIL = 'EMAIL',
    AGENT_TYPE = 'AGENT_TYPE',

    // High Yield Savings 
    START_PRINCIPAL = 'START_PRINCIPAL',
    START_BALANCE = 'START_BALANCE',
    INTEREST = 'INTEREST',
    ACCUMULATED_INTEREST = 'ACCUMULATED_INTEREST',
    END_BALANCE = 'END_BALANCE',
    END_PRINCIPAL = 'END_PRINCIPAL',

    // RentCast
    API_KEY_NAME = 'API_KEY_NAME',
    CAN_MAKE_API_CALL = 'CAN_MAKE_API_CALL',
    API_CALLS_MAKE_THIS_MONTH = 'API_CALLS_MAKE_THIS_MONTH',
    REMAINING_NUMBER_OF_FREE_API_CALLS = 'REMAINING_NUMBER_OF_FREE_API_CALLS',
    DAYS_INTO_BILLING_PERIOD = 'DAYS_INTO_BILLING_PERIOD',
    BILLING_PERIOD = 'BILLING_PERIOD',
    MOST_RECENT_BILLING_DATE = 'MOST_RECENT_BILLING_DATE',
    FIRST_BILLED_ON = 'FIRST_BILLED_ON',
};

// Implement the sortMap with the defined types
export const columnDetails: ColumnsDetails = {
    [TableColumnDetailsEnum.PROPERTY_TYPE]: PropertyTypeColumn,
    [TableColumnDetailsEnum.FULL_ADDRESS]: FullAddressColumn,
    [TableColumnDetailsEnum.STATE]: StateColumn,
    [TableColumnDetailsEnum.ZIP_CODE]: ZipCodeColumn,
    [TableColumnDetailsEnum.ZILLOW_URL]: ZillowUrlColumn,
    [TableColumnDetailsEnum.PRICE]: PriceColumn,
    [TableColumnDetailsEnum.RENT_ESTIMATE]: RentEstimateColumn,
    [TableColumnDetailsEnum.INITIAL_COSTS]: InitialCostsColumn,
    [TableColumnDetailsEnum.LOAN_AMOUNT]: LoanAmountColumn,
    [TableColumnDetailsEnum.DOWN_PAYMENT_AMOUNT]: DownPaymentAmountColumn,
    [TableColumnDetailsEnum.ANNUAL_INTEREST_RATE]: AnnualInterestRateColumn,
    [TableColumnDetailsEnum.ROI]: ROIColumn,
    [TableColumnDetailsEnum.CAP_RATE]: CapRateColumn,
    [TableColumnDetailsEnum.RECURRING_COSTS]: RecurringCostsColumn,
    [TableColumnDetailsEnum.INITIAL_MONTHLY_AMOUNT]: InitialMonthlyPaymentColumn,
    [TableColumnDetailsEnum.MORTGAGE]: MortgageAmountColumn,
    [TableColumnDetailsEnum.MONTHLY_CASH_FLOW]: MonthlyCashFlowColumn,
    [TableColumnDetailsEnum.YEARLY_CASH_FLOW]: YearlyCashFlowColumn,
    [TableColumnDetailsEnum.NUMBER_OF_DAYS_ON_MARKET]: NumberOfDaysOnMarketColumn,
    [TableColumnDetailsEnum.DATE_LISTED]: DateListedColumn,
    [TableColumnDetailsEnum.DATE_CREATED]: DateCreatedColumn,
    [TableColumnDetailsEnum.CITY]: CityColumn,
    [TableColumnDetailsEnum.COUNTY]: CountyColumn,
    [TableColumnDetailsEnum.COUNTRY]: CountryColumn,
    [TableColumnDetailsEnum.STREET_ADDRESS]: StreetAddressColumn,
    [TableColumnDetailsEnum.APARTMENT_NUMBER]: ApartmentNumberColumn,
    [TableColumnDetailsEnum.LONGITUDE]: LongitudeColumn,
    [TableColumnDetailsEnum.LATITUDE]: LatitudeColumn,
    [TableColumnDetailsEnum.ELEMENTARY_SCHOOL_RATING]: ElementarySchoolRatingColumn,
    [TableColumnDetailsEnum.MIDDLE_SCHOOL_RATING]: MiddleSchoolRatingColumn,
    [TableColumnDetailsEnum.HIGH_SCHOOL_RATING]: HighSchoolRatingColumn,
    [TableColumnDetailsEnum.NUMBER_OF_BEDROOMS]: NumberOfBedroomsColumn,
    [TableColumnDetailsEnum.NUMBER_OF_FULL_BATHROOMS]: NumberOfFullBathroomsColumn,
    [TableColumnDetailsEnum.NUMBER_OF_HALF_BATHROOMS]: NumberOfHalfBathroomsColumn,
    [TableColumnDetailsEnum.SQUARE_FEET]: SquareFeetColumn,
    [TableColumnDetailsEnum.ACRES]: AcresColumn,
    [TableColumnDetailsEnum.YEAR_BUILT]: YearBuiltColumn,
    [TableColumnDetailsEnum.HAS_GARAGE]: HasGarageColumn,
    [TableColumnDetailsEnum.HAS_POOL]: HasPoolColumn,
    [TableColumnDetailsEnum.HAS_BASEMENT]: HasBasementColumn,
    [TableColumnDetailsEnum.LISTING_PRICE]: ListingPriceColumn,
    [TableColumnDetailsEnum.ZESTIMATE]: ZestimateColumn,
    [TableColumnDetailsEnum.ZILLOW_RENT_ESTIMATE]: ZillowRentEstimateColumn,
    [TableColumnDetailsEnum.ZESTIMATE_RANGE_LOW]: ZestimateRangeLowColumn,
    [TableColumnDetailsEnum.ZESTIMATE_RANGE_HIGH]: ZestimateRangeHighColumn,
    [TableColumnDetailsEnum.ZILLOW_MONTHLY_PROPERTY_TAX_AMOUNT]: ZillowMonthlyPropertyTaxAmountColumn,
    [TableColumnDetailsEnum.ZILLOW_MONTHLY_HOME_INSURANCE_AMOUNT]: ZillowMonthlyHomeInsuranceAmountColumn,
    [TableColumnDetailsEnum.ZILLOW_MONTHLY_HOA_FEES_AMOUNT]: ZillowMonthlyHOAFeesAmountColumn,
    [TableColumnDetailsEnum.CREATION_TYPE]: CreationTypeColumn,
    [TableColumnDetailsEnum.DESCRIPTION]: DescriptionColumn,
    [TableColumnDetailsEnum.YEAR]: YearColumn,
    [TableColumnDetailsEnum.MONTH]: MonthColumn,
    [TableColumnDetailsEnum.DATE]: DateColumn,
    [TableColumnDetailsEnum.TOTAL_INTEREST_PAID]: TotalInterestPaidColumn,
    [TableColumnDetailsEnum.TOTAL_PRINCIPAL_PAID]: TotalPrincipalPaidColumn,
    [TableColumnDetailsEnum.REMAINING_BALANCE]: RemainingBalanceColumn,
    [TableColumnDetailsEnum.MONTHLY_INCOME]: MonthlyIncomeColumn,
    [TableColumnDetailsEnum.MONTHLY_EXPENSES]: MonthlyExpensesColumn,
    [TableColumnDetailsEnum.ACCUMULATED_CASH_FLOW]: AccumulatedCashFlowColumn,
    [TableColumnDetailsEnum.APPRECIATION_AMOUNT]: AppreciationAmountColumn,
    [TableColumnDetailsEnum.PMI_AMOUNT]: PMIAmountColumn,
    [TableColumnDetailsEnum.INTEREST_PAYMENT]: InterestPaymentColumn,
    [TableColumnDetailsEnum.PRINCIPAL_PAYMENT]: PrincipalPaymentColumn,
    [TableColumnDetailsEnum.PERCENTAGE_OF_INTEREST]: PercentageOfInterestColumn,
    [TableColumnDetailsEnum.PERCENTAGE_OF_PRINCIPAL]: PercentageOfPrincipalColumn,
    [TableColumnDetailsEnum.EQUITY_AMOUNT]: EquityAmountColumn,
    [TableColumnDetailsEnum.NET_OPERATING_INCOME]: NetOperatingIncomeColumn,
    [TableColumnDetailsEnum.ACCUMULATED_NET_OPERATING_INCOME]: AccumulatedNetOperatingIncomeColumn,
    [TableColumnDetailsEnum.CASH_ON_CASH_RETURN]: CashOnCashReturnColumn,
    [TableColumnDetailsEnum.MONTHLY_NET_INCOME]: MonthlyNetIncomeColumn,
    [TableColumnDetailsEnum.ACCUMULATED_NET_INCOME]: AccumulatedNetIncomeColumn,
    [TableColumnDetailsEnum.PROPERTY_MANAGEMENT_AMOUNT]: PropertyManagementAmountColumn,
    [TableColumnDetailsEnum.VACANCY_AMOUNT]: VacancyAmountColumn,
    [TableColumnDetailsEnum.MAINTENANCE_AMOUNT]: MaintenanceAmountColumn,
    [TableColumnDetailsEnum.CAP_EX_RESERVE_AMOUNT]: CapExReserveAmountColumn,
    [TableColumnDetailsEnum.OTHER_EXPENSE_AMOUNT]: OtherExpenseAmountColumn,
    [TableColumnDetailsEnum.OPERATIONAL_COSTS]: OperationalCostsColumn,
    [TableColumnDetailsEnum.PROPERTY_TAX_AMOUNT]: PropertyTaxAmountColumn,
    [TableColumnDetailsEnum.MONTHLY_HOME_INSURANCE_AMOUNT]: MonthlyHomeInsuranceAmountColumn,
    [TableColumnDetailsEnum.MONTHLY_HOA_FEES_AMOUNT]: MonthlyHOAFeesAmountColumn,
    [TableColumnDetailsEnum.FIXED_COSTS]: FixedCostsColumn,
    [TableColumnDetailsEnum.MONTHLY_PAYMENT]: MonthlyPaymentColumn,
    [TableColumnDetailsEnum.MONTHLY_PAYMENT_AND_OPERATIONAL_COSTS]: MonthlyPaymentAndOperationalCostsColumn,
    [TableColumnDetailsEnum.FIRST_NAME]: FirstNameColumn,
    [TableColumnDetailsEnum.LAST_NAME]: LastNameColumn,
    [TableColumnDetailsEnum.FULL_NAME]: FullNameColumn,
    [TableColumnDetailsEnum.WEBSITE]: WebsiteColumn,
    [TableColumnDetailsEnum.COMPANY_NAME]: CompanyNameColumn,
    [TableColumnDetailsEnum.PHONE_NUMBER]: PhoneNumberColumn,
    [TableColumnDetailsEnum.EMAIL]: EmailColumn,
    [TableColumnDetailsEnum.AGENT_TYPE]: AgentTypeColumn,
    [TableColumnDetailsEnum.START_PRINCIPAL]: StartPrincipalColumn,
    [TableColumnDetailsEnum.START_BALANCE]: StartBalanceColumn,
    [TableColumnDetailsEnum.INTEREST]: InterestColumn,
    [TableColumnDetailsEnum.ACCUMULATED_INTEREST]: AccumulatedInterestColumn,
    [TableColumnDetailsEnum.END_BALANCE]: EndBalanceColumn,
    [TableColumnDetailsEnum.END_PRINCIPAL]: EndPrincipalColumn,
    [TableColumnDetailsEnum.API_KEY_NAME]: ApiKeyNameColumn,
    [TableColumnDetailsEnum.CAN_MAKE_API_CALL]: CanMakeApiCallColumn,
    [TableColumnDetailsEnum.API_CALLS_MAKE_THIS_MONTH]: ApiCallsMadeThisMonthColumn,
    [TableColumnDetailsEnum.REMAINING_NUMBER_OF_FREE_API_CALLS]: RemainingNumberOfFreeApiCallsColumn,
    [TableColumnDetailsEnum.DAYS_INTO_BILLING_PERIOD]: DaysIntoBillingPeriodColumn,
    [TableColumnDetailsEnum.BILLING_PERIOD]: BillingPeriodColumn,
    [TableColumnDetailsEnum.MOST_RECENT_BILLING_DATE]: MostRecentBillingDateColumn,
    [TableColumnDetailsEnum.FIRST_BILLED_ON]: FirstBilledOnColumn,
};
