import {
    ColumnsDetails,
    TableColumnDetailsEnum
} from "@realestatemanager/types";
import {
    FirstNameColumn,
    LastNameColumn,
    FullNameColumn,
    WebsiteColumn,
    CompanyNameColumn,
    PhoneNumberColumn,
    EmailColumn,
    AgentTypeColumn
} from "../tablecolumns/AgentTypeColumns";
import {
    StartPrincipalColumn,
    StartBalanceColumn,
    InterestColumn,
    AccumulatedInterestColumn,
    EndBalanceColumn,
    EndPrincipalColumn
} from "../tablecolumns/HighYieldSavingsColumns";
import {
    TotalInterestPaidColumn,
    TotalPrincipalPaidColumn,
    RemainingBalanceColumn,
    MonthlyIncomeColumn,
    MonthlyExpensesColumn,
    AccumulatedCashFlowColumn,
    AppreciationAmountColumn,
    PMIAmountColumn,
    InterestPaymentColumn,
    PrincipalPaymentColumn,
    PercentageOfInterestColumn,
    PercentageOfPrincipalColumn,
    EquityAmountColumn,
    NetOperatingIncomeColumn,
    AccumulatedNetOperatingIncomeColumn,
    CashOnCashReturnColumn,
    MonthlyNetIncomeColumn,
    AccumulatedNetIncomeColumn,
    PropertyManagementAmountColumn,
    VacancyAmountColumn,
    MaintenanceAmountColumn,
    CapExReserveAmountColumn,
    OtherExpenseAmountColumn,
    OperationalCostsColumn,
    PropertyTaxAmountColumn,
    MonthlyHomeInsuranceAmountColumn,
    MonthlyHOAFeesAmountColumn,
    FixedCostsColumn,
    MonthlyPaymentColumn,
    MonthlyPaymentAndOperationalCostsColumn
} from "../tablecolumns/InvestmentBreakdownColumns";
import {
    AcresColumn,
    AnnualInterestRateColumn,
    ApartmentNumberColumn,
    CityColumn,
    CountyColumn,
    CreationTypeColumn,
    DateCreatedColumn,
    DateListedColumn,
    DescriptionColumn,
    DownPaymentAmountColumn,
    ElementarySchoolRatingColumn,
    FullAddressColumn,
    HasBasementColumn,
    HasGarageColumn,
    HasPoolColumn,
    HighSchoolRatingColumn,
    InitialCostsColumn,
    InitialMonthlyPaymentColumn,
    InvestmentBreakdownColumn,
    LatitudeColumn,
    ListingPriceColumn,
    LoanAmountColumn,
    LongitudeColumn,
    MiddleSchoolRatingColumn,
    NumberOfBedroomsColumn,
    NumberOfDaysOnMarketColumn,
    NumberOfFullBathroomsColumn,
    NumberOfHalfBathroomsColumn,
    PriceColumn,
    PropertyStatusColumn,
    PropertyTypeColumn,
    RecurringCostsColumn,
    SquareFeetColumn,
    StreetAddressColumn,
    YearBuiltColumn,
    YearlyCashFlowColumn,
    ZestimateColumn,
    ZestimateRangeHighColumn,
    ZestimateRangeLowColumn,
    ZillowMonthlyHOAFeesAmountColumn,
    ZillowMonthlyHomeInsuranceAmountColumn,
    ZillowMonthlyPropertyTaxAmountColumn,
    ZillowRentEstimateColumn,
    ZillowUrlColumn,
    ZipCodeColumn
} from "../tablecolumns/PropertyListColumns";
import {
    ApiKeyNameColumn,
    CanMakeApiCallColumn,
    ApiCallsMadeThisMonthColumn,
    RemainingNumberOfFreeApiCallsColumn,
    DaysIntoBillingPeriodColumn,
    BillingPeriodColumn,
    MostRecentBillingDateColumn,
    FirstBilledOnColumn
} from "../tablecolumns/RentCastApiDetailsColumns";
import {
    StateColumn,
    RentEstimateColumn,
    ROIColumn,
    CapRateColumn,
    MortgageAmountColumn,
    MonthlyCashFlowColumn,
    CountryColumn,
    YearColumn,
    MonthColumn,
    DateColumn
} from "../tablecolumns/SharedColumns";

// Implement the sortMap with the defined types
export const columnDetails: ColumnsDetails = {
    [TableColumnDetailsEnum.PROPERTY_TYPE]: PropertyTypeColumn,
    [TableColumnDetailsEnum.PROPERTY_STATUS]: PropertyStatusColumn,
    [TableColumnDetailsEnum.FULL_ADDRESS]: FullAddressColumn,
    [TableColumnDetailsEnum.STATE]: StateColumn,
    [TableColumnDetailsEnum.ZIP_CODE]: ZipCodeColumn,
    [TableColumnDetailsEnum.ZILLOW_URL]: ZillowUrlColumn,
    [TableColumnDetailsEnum.PRICE]: PriceColumn,
    [TableColumnDetailsEnum.RENT_ESTIMATE]: RentEstimateColumn,
    [TableColumnDetailsEnum.INITIAL_COSTS]: InitialCostsColumn,
    [TableColumnDetailsEnum.LOAN_AMOUNT]: LoanAmountColumn,
    [TableColumnDetailsEnum.DOWN_PAYMENT_AMOUNT]: DownPaymentAmountColumn,
    [TableColumnDetailsEnum.ANNUAL_INTEREST_RATE]: AnnualInterestRateColumn,
    [TableColumnDetailsEnum.ROI]: ROIColumn,
    [TableColumnDetailsEnum.CAP_RATE]: CapRateColumn,
    [TableColumnDetailsEnum.RECURRING_COSTS]: RecurringCostsColumn,
    [TableColumnDetailsEnum.INITIAL_MONTHLY_AMOUNT]: InitialMonthlyPaymentColumn,
    [TableColumnDetailsEnum.MORTGAGE]: MortgageAmountColumn,
    [TableColumnDetailsEnum.MONTHLY_CASH_FLOW]: MonthlyCashFlowColumn,
    [TableColumnDetailsEnum.YEARLY_CASH_FLOW]: YearlyCashFlowColumn,
    [TableColumnDetailsEnum.NUMBER_OF_DAYS_ON_MARKET]: NumberOfDaysOnMarketColumn,
    [TableColumnDetailsEnum.DATE_LISTED]: DateListedColumn,
    [TableColumnDetailsEnum.DATE_CREATED]: DateCreatedColumn,
    [TableColumnDetailsEnum.CITY]: CityColumn,
    [TableColumnDetailsEnum.COUNTY]: CountyColumn,
    [TableColumnDetailsEnum.COUNTRY]: CountryColumn,
    [TableColumnDetailsEnum.STREET_ADDRESS]: StreetAddressColumn,
    [TableColumnDetailsEnum.APARTMENT_NUMBER]: ApartmentNumberColumn,
    [TableColumnDetailsEnum.LONGITUDE]: LongitudeColumn,
    [TableColumnDetailsEnum.LATITUDE]: LatitudeColumn,
    [TableColumnDetailsEnum.ELEMENTARY_SCHOOL_RATING]: ElementarySchoolRatingColumn,
    [TableColumnDetailsEnum.MIDDLE_SCHOOL_RATING]: MiddleSchoolRatingColumn,
    [TableColumnDetailsEnum.HIGH_SCHOOL_RATING]: HighSchoolRatingColumn,
    [TableColumnDetailsEnum.NUMBER_OF_BEDROOMS]: NumberOfBedroomsColumn,
    [TableColumnDetailsEnum.NUMBER_OF_FULL_BATHROOMS]: NumberOfFullBathroomsColumn,
    [TableColumnDetailsEnum.NUMBER_OF_HALF_BATHROOMS]: NumberOfHalfBathroomsColumn,
    [TableColumnDetailsEnum.SQUARE_FEET]: SquareFeetColumn,
    [TableColumnDetailsEnum.ACRES]: AcresColumn,
    [TableColumnDetailsEnum.YEAR_BUILT]: YearBuiltColumn,
    [TableColumnDetailsEnum.HAS_GARAGE]: HasGarageColumn,
    [TableColumnDetailsEnum.HAS_POOL]: HasPoolColumn,
    [TableColumnDetailsEnum.HAS_BASEMENT]: HasBasementColumn,
    [TableColumnDetailsEnum.LISTING_PRICE]: ListingPriceColumn,
    [TableColumnDetailsEnum.ZESTIMATE]: ZestimateColumn,
    [TableColumnDetailsEnum.ZILLOW_RENT_ESTIMATE]: ZillowRentEstimateColumn,
    [TableColumnDetailsEnum.ZESTIMATE_RANGE_LOW]: ZestimateRangeLowColumn,
    [TableColumnDetailsEnum.ZESTIMATE_RANGE_HIGH]: ZestimateRangeHighColumn,
    [TableColumnDetailsEnum.ZILLOW_MONTHLY_PROPERTY_TAX_AMOUNT]: ZillowMonthlyPropertyTaxAmountColumn,
    [TableColumnDetailsEnum.ZILLOW_MONTHLY_HOME_INSURANCE_AMOUNT]: ZillowMonthlyHomeInsuranceAmountColumn,
    [TableColumnDetailsEnum.ZILLOW_MONTHLY_HOA_FEES_AMOUNT]: ZillowMonthlyHOAFeesAmountColumn,
    [TableColumnDetailsEnum.CREATION_TYPE]: CreationTypeColumn,
    [TableColumnDetailsEnum.DESCRIPTION]: DescriptionColumn,
    [TableColumnDetailsEnum.INVESTMENT_BREAKDOWN_COLUMN]: InvestmentBreakdownColumn,
    [TableColumnDetailsEnum.YEAR]: YearColumn,
    [TableColumnDetailsEnum.MONTH]: MonthColumn,
    [TableColumnDetailsEnum.DATE]: DateColumn,
    [TableColumnDetailsEnum.TOTAL_INTEREST_PAID]: TotalInterestPaidColumn,
    [TableColumnDetailsEnum.TOTAL_PRINCIPAL_PAID]: TotalPrincipalPaidColumn,
    [TableColumnDetailsEnum.REMAINING_BALANCE]: RemainingBalanceColumn,
    [TableColumnDetailsEnum.MONTHLY_INCOME]: MonthlyIncomeColumn,
    [TableColumnDetailsEnum.MONTHLY_EXPENSES]: MonthlyExpensesColumn,
    [TableColumnDetailsEnum.ACCUMULATED_CASH_FLOW]: AccumulatedCashFlowColumn,
    [TableColumnDetailsEnum.APPRECIATION_AMOUNT]: AppreciationAmountColumn,
    [TableColumnDetailsEnum.PMI_AMOUNT]: PMIAmountColumn,
    [TableColumnDetailsEnum.INTEREST_PAYMENT]: InterestPaymentColumn,
    [TableColumnDetailsEnum.PRINCIPAL_PAYMENT]: PrincipalPaymentColumn,
    [TableColumnDetailsEnum.PERCENTAGE_OF_INTEREST]: PercentageOfInterestColumn,
    [TableColumnDetailsEnum.PERCENTAGE_OF_PRINCIPAL]: PercentageOfPrincipalColumn,
    [TableColumnDetailsEnum.EQUITY_AMOUNT]: EquityAmountColumn,
    [TableColumnDetailsEnum.NET_OPERATING_INCOME]: NetOperatingIncomeColumn,
    [TableColumnDetailsEnum.ACCUMULATED_NET_OPERATING_INCOME]: AccumulatedNetOperatingIncomeColumn,
    [TableColumnDetailsEnum.CASH_ON_CASH_RETURN]: CashOnCashReturnColumn,
    [TableColumnDetailsEnum.MONTHLY_NET_INCOME]: MonthlyNetIncomeColumn,
    [TableColumnDetailsEnum.ACCUMULATED_NET_INCOME]: AccumulatedNetIncomeColumn,
    [TableColumnDetailsEnum.PROPERTY_MANAGEMENT_AMOUNT]: PropertyManagementAmountColumn,
    [TableColumnDetailsEnum.VACANCY_AMOUNT]: VacancyAmountColumn,
    [TableColumnDetailsEnum.MAINTENANCE_AMOUNT]: MaintenanceAmountColumn,
    [TableColumnDetailsEnum.CAP_EX_RESERVE_AMOUNT]: CapExReserveAmountColumn,
    [TableColumnDetailsEnum.OTHER_EXPENSE_AMOUNT]: OtherExpenseAmountColumn,
    [TableColumnDetailsEnum.OPERATIONAL_COSTS]: OperationalCostsColumn,
    [TableColumnDetailsEnum.PROPERTY_TAX_AMOUNT]: PropertyTaxAmountColumn,
    [TableColumnDetailsEnum.MONTHLY_HOME_INSURANCE_AMOUNT]: MonthlyHomeInsuranceAmountColumn,
    [TableColumnDetailsEnum.MONTHLY_HOA_FEES_AMOUNT]: MonthlyHOAFeesAmountColumn,
    [TableColumnDetailsEnum.FIXED_COSTS]: FixedCostsColumn,
    [TableColumnDetailsEnum.MONTHLY_PAYMENT]: MonthlyPaymentColumn,
    [TableColumnDetailsEnum.MONTHLY_PAYMENT_AND_OPERATIONAL_COSTS]: MonthlyPaymentAndOperationalCostsColumn,
    [TableColumnDetailsEnum.FIRST_NAME]: FirstNameColumn,
    [TableColumnDetailsEnum.LAST_NAME]: LastNameColumn,
    [TableColumnDetailsEnum.FULL_NAME]: FullNameColumn,
    [TableColumnDetailsEnum.WEBSITE]: WebsiteColumn,
    [TableColumnDetailsEnum.COMPANY_NAME]: CompanyNameColumn,
    [TableColumnDetailsEnum.PHONE_NUMBER]: PhoneNumberColumn,
    [TableColumnDetailsEnum.EMAIL]: EmailColumn,
    [TableColumnDetailsEnum.AGENT_TYPE]: AgentTypeColumn,
    [TableColumnDetailsEnum.START_PRINCIPAL]: StartPrincipalColumn,
    [TableColumnDetailsEnum.START_BALANCE]: StartBalanceColumn,
    [TableColumnDetailsEnum.INTEREST]: InterestColumn,
    [TableColumnDetailsEnum.ACCUMULATED_INTEREST]: AccumulatedInterestColumn,
    [TableColumnDetailsEnum.END_BALANCE]: EndBalanceColumn,
    [TableColumnDetailsEnum.END_PRINCIPAL]: EndPrincipalColumn,
    [TableColumnDetailsEnum.API_KEY_NAME]: ApiKeyNameColumn,
    [TableColumnDetailsEnum.CAN_MAKE_API_CALL]: CanMakeApiCallColumn,
    [TableColumnDetailsEnum.API_CALLS_MAKE_THIS_MONTH]: ApiCallsMadeThisMonthColumn,
    [TableColumnDetailsEnum.REMAINING_NUMBER_OF_FREE_API_CALLS]: RemainingNumberOfFreeApiCallsColumn,
    [TableColumnDetailsEnum.DAYS_INTO_BILLING_PERIOD]: DaysIntoBillingPeriodColumn,
    [TableColumnDetailsEnum.BILLING_PERIOD]: BillingPeriodColumn,
    [TableColumnDetailsEnum.MOST_RECENT_BILLING_DATE]: MostRecentBillingDateColumn,
    [TableColumnDetailsEnum.FIRST_BILLED_ON]: FirstBilledOnColumn,
};
